// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: log_sync/v1/pnl.proto

package log_sync

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PnlServiceClient is the client API for PnlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PnlServiceClient interface {
	// ListPnlSummaries will return pnl summaries.
	ListPnlSummaries(ctx context.Context, in *ListPnlSummariesRequest, opts ...grpc.CallOption) (*ListPnlSummariesResponse, error)
}

type pnlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPnlServiceClient(cc grpc.ClientConnInterface) PnlServiceClient {
	return &pnlServiceClient{cc}
}

func (c *pnlServiceClient) ListPnlSummaries(ctx context.Context, in *ListPnlSummariesRequest, opts ...grpc.CallOption) (*ListPnlSummariesResponse, error) {
	out := new(ListPnlSummariesResponse)
	err := c.cc.Invoke(ctx, "/log_sync.v1.pnl.PnlService/ListPnlSummaries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PnlServiceServer is the server API for PnlService service.
// All implementations must embed UnimplementedPnlServiceServer
// for forward compatibility
type PnlServiceServer interface {
	// ListPnlSummaries will return pnl summaries.
	ListPnlSummaries(context.Context, *ListPnlSummariesRequest) (*ListPnlSummariesResponse, error)
	mustEmbedUnimplementedPnlServiceServer()
}

// UnimplementedPnlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPnlServiceServer struct {
}

func (UnimplementedPnlServiceServer) ListPnlSummaries(context.Context, *ListPnlSummariesRequest) (*ListPnlSummariesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPnlSummaries not implemented")
}
func (UnimplementedPnlServiceServer) mustEmbedUnimplementedPnlServiceServer() {}

// UnsafePnlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PnlServiceServer will
// result in compilation errors.
type UnsafePnlServiceServer interface {
	mustEmbedUnimplementedPnlServiceServer()
}

func RegisterPnlServiceServer(s grpc.ServiceRegistrar, srv PnlServiceServer) {
	s.RegisterService(&PnlService_ServiceDesc, srv)
}

func _PnlService_ListPnlSummaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPnlSummariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PnlServiceServer).ListPnlSummaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/log_sync.v1.pnl.PnlService/ListPnlSummaries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PnlServiceServer).ListPnlSummaries(ctx, req.(*ListPnlSummariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PnlService_ServiceDesc is the grpc.ServiceDesc for PnlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PnlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "log_sync.v1.pnl.PnlService",
	HandlerType: (*PnlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPnlSummaries",
			Handler:    _PnlService_ListPnlSummaries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log_sync/v1/pnl.proto",
}
