// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Stock {
    /// Stock ID
    #[prost(uint64, tag="1")]
    pub id: u64,
    /// 주식 심볼 (ISIN 코드)
    #[prost(string, tag="2")]
    pub symbol: ::prost::alloc::string::String,
    /// 주식 코드
    #[prost(string, tag="3")]
    pub code: ::prost::alloc::string::String,
    /// 주식 이름
    #[prost(string, tag="4")]
    pub name: ::prost::alloc::string::String,
    /// 전일 종가
    #[prost(string, tag="5")]
    pub prev_close: ::prost::alloc::string::String,
    /// 현재가
    #[prost(string, tag="6")]
    pub last_price: ::prost::alloc::string::String,
    /// 시장 구분
    #[prost(enumeration="MarketType", tag="7")]
    pub market_type: i32,
    /// 상장 주식 수
    #[prost(int64, tag="8")]
    pub listed_shares: i64,
    /// Tick 크기 (원 단위)
    #[prost(int64, tag="9")]
    pub tick_size: i64,
    /// 거래 가능 여부
    #[prost(bool, tag="10")]
    pub tradable: bool,
    /// 공매도 가능 여부
    #[prost(bool, tag="11")]
    pub short_sellable: bool,
    /// 신용 거래 가능 여부
    #[prost(bool, tag="12")]
    pub margin_tradable: bool,
    /// 섹터 코드
    #[prost(string, tag="13")]
    pub sector_code: ::prost::alloc::string::String,
    /// 섹터 이름
    #[prost(string, tag="14")]
    pub sector_name: ::prost::alloc::string::String,
}
// ========== Request/Response Messages ==========

/// GetStock
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetStockRequest {
    #[prost(string, tag="1")]
    pub stock: ::prost::alloc::string::String,
}
/// ListStocks
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListStocksRequest {
    /// 페이지 크기 (optional)
    #[prost(uint32, optional, tag="1")]
    pub page_size: ::core::option::Option<u32>,
    /// 페이지 토큰 (optional, for pagination)
    #[prost(string, optional, tag="2")]
    pub page_token: ::core::option::Option<::prost::alloc::string::String>,
    /// 필터링 조건 (optional, AIP-160)
    #[prost(string, tag="3")]
    pub filter: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListStocksResponse {
    /// 주식 목록
    #[prost(message, repeated, tag="1")]
    pub stocks: ::prost::alloc::vec::Vec<Stock>,
    /// 다음 페이지 토큰
    #[prost(string, tag="2")]
    pub next_page_token: ::prost::alloc::string::String,
}
/// 시장 구분
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MarketType {
    Unspecified = 0,
    Kospi = 1,
    Kosdaq = 2,
    Konex = 3,
}
impl MarketType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            MarketType::Unspecified => "MARKET_TYPE_UNSPECIFIED",
            MarketType::Kospi => "MARKET_TYPE_KOSPI",
            MarketType::Kosdaq => "MARKET_TYPE_KOSDAQ",
            MarketType::Konex => "MARKET_TYPE_KONEX",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MARKET_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "MARKET_TYPE_KOSPI" => Some(Self::Kospi),
            "MARKET_TYPE_KOSDAQ" => Some(Self::Kosdaq),
            "MARKET_TYPE_KONEX" => Some(Self::Konex),
            _ => None,
        }
    }
}
include!("master_sync.v1.stock.tonic.rs");
include!("master_sync.v1.stock.serde.rs");
// @@protoc_insertion_point(module)