// Code generated by protoc-gen-go-grpc-mock. DO NOT EDIT.
// source: mmm/v1/etf.proto

package mmm

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockEtfServiceClient is a mock of EtfServiceClient interface.
type MockEtfServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockEtfServiceClientMockRecorder
}

// MockEtfServiceClientMockRecorder is the mock recorder for MockEtfServiceClient.
type MockEtfServiceClientMockRecorder struct {
	mock *MockEtfServiceClient
}

// NewMockEtfServiceClient creates a new mock instance.
func NewMockEtfServiceClient(ctrl *gomock.Controller) *MockEtfServiceClient {
	mock := &MockEtfServiceClient{ctrl: ctrl}
	mock.recorder = &MockEtfServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEtfServiceClient) EXPECT() *MockEtfServiceClientMockRecorder {
	return m.recorder
}

// GetETFManager mocks base method.
func (m *MockEtfServiceClient) GetETFManager(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (*ETFManagerDetail, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetETFManager", varargs...)
	ret0, _ := ret[0].(*ETFManagerDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetETFManager indicates an expected call of GetETFManager.
func (mr *MockEtfServiceClientMockRecorder) GetETFManager(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetETFManager", reflect.TypeOf((*MockEtfServiceClient)(nil).GetETFManager), varargs...)
}

// MockEtfServiceServer is a mock of EtfServiceServer interface.
type MockEtfServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockEtfServiceServerMockRecorder
}

// MockEtfServiceServerMockRecorder is the mock recorder for MockEtfServiceServer.
type MockEtfServiceServerMockRecorder struct {
	mock *MockEtfServiceServer
}

// NewMockEtfServiceServer creates a new mock instance.
func NewMockEtfServiceServer(ctrl *gomock.Controller) *MockEtfServiceServer {
	mock := &MockEtfServiceServer{ctrl: ctrl}
	mock.recorder = &MockEtfServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEtfServiceServer) EXPECT() *MockEtfServiceServerMockRecorder {
	return m.recorder
}

// GetETFManager mocks base method.
func (m *MockEtfServiceServer) GetETFManager(ctx context.Context, in *CodeRequest) (*ETFManagerDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetETFManager", ctx, in)
	ret0, _ := ret[0].(*ETFManagerDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetETFManager indicates an expected call of GetETFManager.
func (mr *MockEtfServiceServerMockRecorder) GetETFManager(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetETFManager", reflect.TypeOf((*MockEtfServiceServer)(nil).GetETFManager), ctx, in)
}
