// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: kdo/v1/auto_amend.proto

package kdo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AutoAmendServiceClient is the client API for AutoAmendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutoAmendServiceClient interface {
	// 등록된 주문 조회
	GetOrder(ctx context.Context, in *GetAutoAmendOrderRequest, opts ...grpc.CallOption) (*AutoAmendOrder, error)
	// 등록된 주문 목록 조회
	ListOrders(ctx context.Context, in *ListAutoAmendOrdersRequest, opts ...grpc.CallOption) (*ListAutoAmendOrdersResponse, error)
	// 설정 업데이트
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*AutoAmendOrder, error)
	// 이벤트 스트리밍
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (AutoAmendService_StreamEventsClient, error)
}

type autoAmendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAutoAmendServiceClient(cc grpc.ClientConnInterface) AutoAmendServiceClient {
	return &autoAmendServiceClient{cc}
}

func (c *autoAmendServiceClient) GetOrder(ctx context.Context, in *GetAutoAmendOrderRequest, opts ...grpc.CallOption) (*AutoAmendOrder, error) {
	out := new(AutoAmendOrder)
	err := c.cc.Invoke(ctx, "/kdo.v1.auto_amend.AutoAmendService/GetOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoAmendServiceClient) ListOrders(ctx context.Context, in *ListAutoAmendOrdersRequest, opts ...grpc.CallOption) (*ListAutoAmendOrdersResponse, error) {
	out := new(ListAutoAmendOrdersResponse)
	err := c.cc.Invoke(ctx, "/kdo.v1.auto_amend.AutoAmendService/ListOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoAmendServiceClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*AutoAmendOrder, error) {
	out := new(AutoAmendOrder)
	err := c.cc.Invoke(ctx, "/kdo.v1.auto_amend.AutoAmendService/UpdateConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoAmendServiceClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (AutoAmendService_StreamEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AutoAmendService_ServiceDesc.Streams[0], "/kdo.v1.auto_amend.AutoAmendService/StreamEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &autoAmendServiceStreamEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AutoAmendService_StreamEventsClient interface {
	Recv() (*AutoAmendEvent, error)
	grpc.ClientStream
}

type autoAmendServiceStreamEventsClient struct {
	grpc.ClientStream
}

func (x *autoAmendServiceStreamEventsClient) Recv() (*AutoAmendEvent, error) {
	m := new(AutoAmendEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AutoAmendServiceServer is the server API for AutoAmendService service.
// All implementations must embed UnimplementedAutoAmendServiceServer
// for forward compatibility
type AutoAmendServiceServer interface {
	// 등록된 주문 조회
	GetOrder(context.Context, *GetAutoAmendOrderRequest) (*AutoAmendOrder, error)
	// 등록된 주문 목록 조회
	ListOrders(context.Context, *ListAutoAmendOrdersRequest) (*ListAutoAmendOrdersResponse, error)
	// 설정 업데이트
	UpdateConfig(context.Context, *UpdateConfigRequest) (*AutoAmendOrder, error)
	// 이벤트 스트리밍
	StreamEvents(*StreamEventsRequest, AutoAmendService_StreamEventsServer) error
	mustEmbedUnimplementedAutoAmendServiceServer()
}

// UnimplementedAutoAmendServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAutoAmendServiceServer struct {
}

func (UnimplementedAutoAmendServiceServer) GetOrder(context.Context, *GetAutoAmendOrderRequest) (*AutoAmendOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedAutoAmendServiceServer) ListOrders(context.Context, *ListAutoAmendOrdersRequest) (*ListAutoAmendOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrders not implemented")
}
func (UnimplementedAutoAmendServiceServer) UpdateConfig(context.Context, *UpdateConfigRequest) (*AutoAmendOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedAutoAmendServiceServer) StreamEvents(*StreamEventsRequest, AutoAmendService_StreamEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedAutoAmendServiceServer) mustEmbedUnimplementedAutoAmendServiceServer() {}

// UnsafeAutoAmendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutoAmendServiceServer will
// result in compilation errors.
type UnsafeAutoAmendServiceServer interface {
	mustEmbedUnimplementedAutoAmendServiceServer()
}

func RegisterAutoAmendServiceServer(s grpc.ServiceRegistrar, srv AutoAmendServiceServer) {
	s.RegisterService(&AutoAmendService_ServiceDesc, srv)
}

func _AutoAmendService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAutoAmendOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoAmendServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.auto_amend.AutoAmendService/GetOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoAmendServiceServer).GetOrder(ctx, req.(*GetAutoAmendOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoAmendService_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAutoAmendOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoAmendServiceServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.auto_amend.AutoAmendService/ListOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoAmendServiceServer).ListOrders(ctx, req.(*ListAutoAmendOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoAmendService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoAmendServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.auto_amend.AutoAmendService/UpdateConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoAmendServiceServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoAmendService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AutoAmendServiceServer).StreamEvents(m, &autoAmendServiceStreamEventsServer{stream})
}

type AutoAmendService_StreamEventsServer interface {
	Send(*AutoAmendEvent) error
	grpc.ServerStream
}

type autoAmendServiceStreamEventsServer struct {
	grpc.ServerStream
}

func (x *autoAmendServiceStreamEventsServer) Send(m *AutoAmendEvent) error {
	return x.ServerStream.SendMsg(m)
}

// AutoAmendService_ServiceDesc is the grpc.ServiceDesc for AutoAmendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AutoAmendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kdo.v1.auto_amend.AutoAmendService",
	HandlerType: (*AutoAmendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrder",
			Handler:    _AutoAmendService_GetOrder_Handler,
		},
		{
			MethodName: "ListOrders",
			Handler:    _AutoAmendService_ListOrders_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _AutoAmendService_UpdateConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _AutoAmendService_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kdo/v1/auto_amend.proto",
}
