// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: kdo/v1/common.proto

package kdo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 주문 방향
type OrderSide int32

const (
	OrderSide_ORDER_SIDE_UNSPECIFIED OrderSide = 0
	OrderSide_ORDER_SIDE_BID         OrderSide = 1 // 매수
	OrderSide_ORDER_SIDE_ASK         OrderSide = 2 // 매도
)

// Enum value maps for OrderSide.
var (
	OrderSide_name = map[int32]string{
		0: "ORDER_SIDE_UNSPECIFIED",
		1: "ORDER_SIDE_BID",
		2: "ORDER_SIDE_ASK",
	}
	OrderSide_value = map[string]int32{
		"ORDER_SIDE_UNSPECIFIED": 0,
		"ORDER_SIDE_BID":         1,
		"ORDER_SIDE_ASK":         2,
	}
)

func (x OrderSide) Enum() *OrderSide {
	p := new(OrderSide)
	*p = x
	return p
}

func (x OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_kdo_v1_common_proto_enumTypes[0].Descriptor()
}

func (OrderSide) Type() protoreflect.EnumType {
	return &file_kdo_v1_common_proto_enumTypes[0]
}

func (x OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSide.Descriptor instead.
func (OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_kdo_v1_common_proto_rawDescGZIP(), []int{0}
}

// 시장 유형
type MarketType int32

const (
	MarketType_MARKET_TYPE_UNSPECIFIED MarketType = 0
	// KOSPI
	MarketType_MARKET_TYPE_KOSPI MarketType = 1
	// KOSDAQ
	MarketType_MARKET_TYPE_KOSDAQ MarketType = 2
	// 파생상품
	MarketType_MARKET_TYPE_DERIVATIVE MarketType = 3
)

// Enum value maps for MarketType.
var (
	MarketType_name = map[int32]string{
		0: "MARKET_TYPE_UNSPECIFIED",
		1: "MARKET_TYPE_KOSPI",
		2: "MARKET_TYPE_KOSDAQ",
		3: "MARKET_TYPE_DERIVATIVE",
	}
	MarketType_value = map[string]int32{
		"MARKET_TYPE_UNSPECIFIED": 0,
		"MARKET_TYPE_KOSPI":       1,
		"MARKET_TYPE_KOSDAQ":      2,
		"MARKET_TYPE_DERIVATIVE":  3,
	}
)

func (x MarketType) Enum() *MarketType {
	p := new(MarketType)
	*p = x
	return p
}

func (x MarketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarketType) Descriptor() protoreflect.EnumDescriptor {
	return file_kdo_v1_common_proto_enumTypes[1].Descriptor()
}

func (MarketType) Type() protoreflect.EnumType {
	return &file_kdo_v1_common_proto_enumTypes[1]
}

func (x MarketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarketType.Descriptor instead.
func (MarketType) EnumDescriptor() ([]byte, []int) {
	return file_kdo_v1_common_proto_rawDescGZIP(), []int{1}
}

// 상품 타입
type ProductType int32

const (
	ProductType_PRODUCT_TYPE_UNSPECIFIED ProductType = 0
	ProductType_PRODUCT_TYPE_STOCK       ProductType = 1
	ProductType_PRODUCT_TYPE_FUTURES     ProductType = 2
	ProductType_PRODUCT_TYPE_ETF         ProductType = 3
	ProductType_PRODUCT_TYPE_CASH        ProductType = 4
)

// Enum value maps for ProductType.
var (
	ProductType_name = map[int32]string{
		0: "PRODUCT_TYPE_UNSPECIFIED",
		1: "PRODUCT_TYPE_STOCK",
		2: "PRODUCT_TYPE_FUTURES",
		3: "PRODUCT_TYPE_ETF",
		4: "PRODUCT_TYPE_CASH",
	}
	ProductType_value = map[string]int32{
		"PRODUCT_TYPE_UNSPECIFIED": 0,
		"PRODUCT_TYPE_STOCK":       1,
		"PRODUCT_TYPE_FUTURES":     2,
		"PRODUCT_TYPE_ETF":         3,
		"PRODUCT_TYPE_CASH":        4,
	}
)

func (x ProductType) Enum() *ProductType {
	p := new(ProductType)
	*p = x
	return p
}

func (x ProductType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductType) Descriptor() protoreflect.EnumDescriptor {
	return file_kdo_v1_common_proto_enumTypes[2].Descriptor()
}

func (ProductType) Type() protoreflect.EnumType {
	return &file_kdo_v1_common_proto_enumTypes[2]
}

func (x ProductType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductType.Descriptor instead.
func (ProductType) EnumDescriptor() ([]byte, []int) {
	return file_kdo_v1_common_proto_rawDescGZIP(), []int{2}
}

// 거래 세션 타입
type TradingSession int32

const (
	TradingSession_TRADING_SESSION_UNSPECIFIED     TradingSession = 0
	TradingSession_TRADING_SESSION_PRE_MARKET      TradingSession = 1 // 장 시작 전
	TradingSession_TRADING_SESSION_OPENING_AUCTION TradingSession = 2 // 시가 동시호가 (08:30 ~ 09:00)
	TradingSession_TRADING_SESSION_REGULAR         TradingSession = 3 // 장중 (09:00 ~ 15:20)
	TradingSession_TRADING_SESSION_CLOSING_AUCTION TradingSession = 4 // 종가 동시호가 (15:20 ~ 15:30)
	TradingSession_TRADING_SESSION_CLOSED          TradingSession = 5 // 장 종료
)

// Enum value maps for TradingSession.
var (
	TradingSession_name = map[int32]string{
		0: "TRADING_SESSION_UNSPECIFIED",
		1: "TRADING_SESSION_PRE_MARKET",
		2: "TRADING_SESSION_OPENING_AUCTION",
		3: "TRADING_SESSION_REGULAR",
		4: "TRADING_SESSION_CLOSING_AUCTION",
		5: "TRADING_SESSION_CLOSED",
	}
	TradingSession_value = map[string]int32{
		"TRADING_SESSION_UNSPECIFIED":     0,
		"TRADING_SESSION_PRE_MARKET":      1,
		"TRADING_SESSION_OPENING_AUCTION": 2,
		"TRADING_SESSION_REGULAR":         3,
		"TRADING_SESSION_CLOSING_AUCTION": 4,
		"TRADING_SESSION_CLOSED":          5,
	}
)

func (x TradingSession) Enum() *TradingSession {
	p := new(TradingSession)
	*p = x
	return p
}

func (x TradingSession) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TradingSession) Descriptor() protoreflect.EnumDescriptor {
	return file_kdo_v1_common_proto_enumTypes[3].Descriptor()
}

func (TradingSession) Type() protoreflect.EnumType {
	return &file_kdo_v1_common_proto_enumTypes[3]
}

func (x TradingSession) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TradingSession.Descriptor instead.
func (TradingSession) EnumDescriptor() ([]byte, []int) {
	return file_kdo_v1_common_proto_rawDescGZIP(), []int{3}
}

// 호가조건코드 (KRX)
// 주문 체결 방식을 지정하는 조건
type OrderConditionType int32

const (
	// 미지정 (기본값: FAS로 처리, 하위 호환)
	OrderConditionType_ORDER_CONDITION_TYPE_UNSPECIFIED OrderConditionType = 0
	// Fill-and-Store: 체결 후 잔량은 호가창에 유지 (일반 지정가) — KRX code "0"
	OrderConditionType_ORDER_CONDITION_TYPE_FAS OrderConditionType = 1
	// Fill-and-Kill (IOC): 체결 후 잔량 즉시 취소 — KRX code "3"
	OrderConditionType_ORDER_CONDITION_TYPE_FAK OrderConditionType = 2
	// Fill-or-Kill: 전량 체결 아니면 전량 취소 — KRX code "4"
	OrderConditionType_ORDER_CONDITION_TYPE_FOK OrderConditionType = 3
)

// Enum value maps for OrderConditionType.
var (
	OrderConditionType_name = map[int32]string{
		0: "ORDER_CONDITION_TYPE_UNSPECIFIED",
		1: "ORDER_CONDITION_TYPE_FAS",
		2: "ORDER_CONDITION_TYPE_FAK",
		3: "ORDER_CONDITION_TYPE_FOK",
	}
	OrderConditionType_value = map[string]int32{
		"ORDER_CONDITION_TYPE_UNSPECIFIED": 0,
		"ORDER_CONDITION_TYPE_FAS":         1,
		"ORDER_CONDITION_TYPE_FAK":         2,
		"ORDER_CONDITION_TYPE_FOK":         3,
	}
)

func (x OrderConditionType) Enum() *OrderConditionType {
	p := new(OrderConditionType)
	*p = x
	return p
}

func (x OrderConditionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderConditionType) Descriptor() protoreflect.EnumDescriptor {
	return file_kdo_v1_common_proto_enumTypes[4].Descriptor()
}

func (OrderConditionType) Type() protoreflect.EnumType {
	return &file_kdo_v1_common_proto_enumTypes[4]
}

func (x OrderConditionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderConditionType.Descriptor instead.
func (OrderConditionType) EnumDescriptor() ([]byte, []int) {
	return file_kdo_v1_common_proto_rawDescGZIP(), []int{4}
}

// 자동정정 전략 유형
type AmendMethodType int32

const (
	// 미지정 (기본값: TIMED_MARKET으로 처리)
	AmendMethodType_AMEND_METHOD_TYPE_UNSPECIFIED AmendMethodType = 0
	// 적극적 정정: 반대편 잔량 비율이 임계값 이상이면 즉시 체결 시도
	AmendMethodType_AMEND_METHOD_TYPE_AGGRESSIVE AmendMethodType = 1
	// 회피적 정정: tick_offset 만큼 가격을 조정하여 미체결 유지
	AmendMethodType_AMEND_METHOD_TYPE_EVASIVE AmendMethodType = 2
	// 최우선 호가: 상대방 최우선 호가로 정정
	AmendMethodType_AMEND_METHOD_TYPE_BEST_PRICE AmendMethodType = 3
	// 손절 정정: tick_threshold 이상 불리해지면 시장가로 전환
	AmendMethodType_AMEND_METHOD_TYPE_STOP_LOSS AmendMethodType = 4
	// 시간 제한 시장가: timeout 후 시장가로 전환
	AmendMethodType_AMEND_METHOD_TYPE_TIMED_MARKET AmendMethodType = 5
)

// Enum value maps for AmendMethodType.
var (
	AmendMethodType_name = map[int32]string{
		0: "AMEND_METHOD_TYPE_UNSPECIFIED",
		1: "AMEND_METHOD_TYPE_AGGRESSIVE",
		2: "AMEND_METHOD_TYPE_EVASIVE",
		3: "AMEND_METHOD_TYPE_BEST_PRICE",
		4: "AMEND_METHOD_TYPE_STOP_LOSS",
		5: "AMEND_METHOD_TYPE_TIMED_MARKET",
	}
	AmendMethodType_value = map[string]int32{
		"AMEND_METHOD_TYPE_UNSPECIFIED":  0,
		"AMEND_METHOD_TYPE_AGGRESSIVE":   1,
		"AMEND_METHOD_TYPE_EVASIVE":      2,
		"AMEND_METHOD_TYPE_BEST_PRICE":   3,
		"AMEND_METHOD_TYPE_STOP_LOSS":    4,
		"AMEND_METHOD_TYPE_TIMED_MARKET": 5,
	}
)

func (x AmendMethodType) Enum() *AmendMethodType {
	p := new(AmendMethodType)
	*p = x
	return p
}

func (x AmendMethodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AmendMethodType) Descriptor() protoreflect.EnumDescriptor {
	return file_kdo_v1_common_proto_enumTypes[5].Descriptor()
}

func (AmendMethodType) Type() protoreflect.EnumType {
	return &file_kdo_v1_common_proto_enumTypes[5]
}

func (x AmendMethodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AmendMethodType.Descriptor instead.
func (AmendMethodType) EnumDescriptor() ([]byte, []int) {
	return file_kdo_v1_common_proto_rawDescGZIP(), []int{5}
}

// ETF 가격 산출 방식
type EtfPricing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Method:
	//
	//	*EtfPricing_PdfNavHedge
	//	*EtfPricing_IndexTrackingHedge
	//	*EtfPricing_FutureBasis
	//	*EtfPricing_LeverageFuture
	//	*EtfPricing_PdfDecomposeHedge
	Method isEtfPricing_Method `protobuf_oneof:"method"`
}

func (x *EtfPricing) Reset() {
	*x = EtfPricing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kdo_v1_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EtfPricing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtfPricing) ProtoMessage() {}

func (x *EtfPricing) ProtoReflect() protoreflect.Message {
	mi := &file_kdo_v1_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtfPricing.ProtoReflect.Descriptor instead.
func (*EtfPricing) Descriptor() ([]byte, []int) {
	return file_kdo_v1_common_proto_rawDescGZIP(), []int{0}
}

func (m *EtfPricing) GetMethod() isEtfPricing_Method {
	if m != nil {
		return m.Method
	}
	return nil
}

func (x *EtfPricing) GetPdfNavHedge() *PdfNavHedgePricing {
	if x, ok := x.GetMethod().(*EtfPricing_PdfNavHedge); ok {
		return x.PdfNavHedge
	}
	return nil
}

func (x *EtfPricing) GetIndexTrackingHedge() *IndexTrackingHedgePricing {
	if x, ok := x.GetMethod().(*EtfPricing_IndexTrackingHedge); ok {
		return x.IndexTrackingHedge
	}
	return nil
}

func (x *EtfPricing) GetFutureBasis() *FutureBasis {
	if x, ok := x.GetMethod().(*EtfPricing_FutureBasis); ok {
		return x.FutureBasis
	}
	return nil
}

func (x *EtfPricing) GetLeverageFuture() *LeverageFuturePricing {
	if x, ok := x.GetMethod().(*EtfPricing_LeverageFuture); ok {
		return x.LeverageFuture
	}
	return nil
}

func (x *EtfPricing) GetPdfDecomposeHedge() *PdfDecomposeHedgePricing {
	if x, ok := x.GetMethod().(*EtfPricing_PdfDecomposeHedge); ok {
		return x.PdfDecomposeHedge
	}
	return nil
}

type isEtfPricing_Method interface {
	isEtfPricing_Method()
}

type EtfPricing_PdfNavHedge struct {
	// 분해 헷지 방식
	PdfNavHedge *PdfNavHedgePricing `protobuf:"bytes,1,opt,name=pdf_nav_hedge,json=pdfNavHedge,proto3,oneof"`
}

type EtfPricing_IndexTrackingHedge struct {
	// 선물 헷지 방식
	IndexTrackingHedge *IndexTrackingHedgePricing `protobuf:"bytes,2,opt,name=index_tracking_hedge,json=indexTrackingHedge,proto3,oneof"`
}

type EtfPricing_FutureBasis struct {
	FutureBasis *FutureBasis `protobuf:"bytes,3,opt,name=future_basis,json=futureBasis,proto3,oneof"`
}

type EtfPricing_LeverageFuture struct {
	// 레버리지 선물 방식
	LeverageFuture *LeverageFuturePricing `protobuf:"bytes,4,opt,name=leverage_future,json=leverageFuture,proto3,oneof"`
}

type EtfPricing_PdfDecomposeHedge struct {
	// PDF 재귀 분해 헷지 방식: leaf가 단일 종목으로 귀결되는 ETF에 대한 프라이싱
	PdfDecomposeHedge *PdfDecomposeHedgePricing `protobuf:"bytes,5,opt,name=pdf_decompose_hedge,json=pdfDecomposeHedge,proto3,oneof"`
}

func (*EtfPricing_PdfNavHedge) isEtfPricing_Method() {}

func (*EtfPricing_IndexTrackingHedge) isEtfPricing_Method() {}

func (*EtfPricing_FutureBasis) isEtfPricing_Method() {}

func (*EtfPricing_LeverageFuture) isEtfPricing_Method() {}

func (*EtfPricing_PdfDecomposeHedge) isEtfPricing_Method() {}

// 분해 헷지 가격 산출 (추가 파라미터 없음)
type PdfNavHedgePricing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PdfNavHedgePricing) Reset() {
	*x = PdfNavHedgePricing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kdo_v1_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PdfNavHedgePricing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PdfNavHedgePricing) ProtoMessage() {}

func (x *PdfNavHedgePricing) ProtoReflect() protoreflect.Message {
	mi := &file_kdo_v1_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PdfNavHedgePricing.ProtoReflect.Descriptor instead.
func (*PdfNavHedgePricing) Descriptor() ([]byte, []int) {
	return file_kdo_v1_common_proto_rawDescGZIP(), []int{1}
}

// 선물 헷지 가격 산출
type IndexTrackingHedgePricing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IndexTrackingHedgePricing) Reset() {
	*x = IndexTrackingHedgePricing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kdo_v1_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexTrackingHedgePricing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexTrackingHedgePricing) ProtoMessage() {}

func (x *IndexTrackingHedgePricing) ProtoReflect() protoreflect.Message {
	mi := &file_kdo_v1_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexTrackingHedgePricing.ProtoReflect.Descriptor instead.
func (*IndexTrackingHedgePricing) Descriptor() ([]byte, []int) {
	return file_kdo_v1_common_proto_rawDescGZIP(), []int{2}
}

type FutureBasis struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrevIndex string `protobuf:"bytes,1,opt,name=prev_index,json=prevIndex,proto3" json:"prev_index,omitempty"`
}

func (x *FutureBasis) Reset() {
	*x = FutureBasis{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kdo_v1_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FutureBasis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FutureBasis) ProtoMessage() {}

func (x *FutureBasis) ProtoReflect() protoreflect.Message {
	mi := &file_kdo_v1_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FutureBasis.ProtoReflect.Descriptor instead.
func (*FutureBasis) Descriptor() ([]byte, []int) {
	return file_kdo_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *FutureBasis) GetPrevIndex() string {
	if x != nil {
		return x.PrevIndex
	}
	return ""
}

// 레버리지 선물 가격 산출
type LeverageFuturePricing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 기초지수 전일종가
	PrevIndex float64 `protobuf:"fixed64,1,opt,name=prev_index,json=prevIndex,proto3" json:"prev_index,omitempty"`
	// 선물 전일종가
	PrevFuture float64 `protobuf:"fixed64,2,opt,name=prev_future,json=prevFuture,proto3" json:"prev_future,omitempty"`
}

func (x *LeverageFuturePricing) Reset() {
	*x = LeverageFuturePricing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kdo_v1_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeverageFuturePricing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeverageFuturePricing) ProtoMessage() {}

func (x *LeverageFuturePricing) ProtoReflect() protoreflect.Message {
	mi := &file_kdo_v1_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeverageFuturePricing.ProtoReflect.Descriptor instead.
func (*LeverageFuturePricing) Descriptor() ([]byte, []int) {
	return file_kdo_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *LeverageFuturePricing) GetPrevIndex() float64 {
	if x != nil {
		return x.PrevIndex
	}
	return 0
}

func (x *LeverageFuturePricing) GetPrevFuture() float64 {
	if x != nil {
		return x.PrevFuture
	}
	return 0
}

// PDF 재귀 분해 헷지 가격 산출
// nav = leaf_price × ratio_per_share
type PdfDecomposeHedgePricing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ETF 1주당 leaf 종목 환산 수량 (ETF-side 부호)
	RatioPerShare float64 `protobuf:"fixed64,1,opt,name=ratio_per_share,json=ratioPerShare,proto3" json:"ratio_per_share,omitempty"`
}

func (x *PdfDecomposeHedgePricing) Reset() {
	*x = PdfDecomposeHedgePricing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kdo_v1_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PdfDecomposeHedgePricing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PdfDecomposeHedgePricing) ProtoMessage() {}

func (x *PdfDecomposeHedgePricing) ProtoReflect() protoreflect.Message {
	mi := &file_kdo_v1_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PdfDecomposeHedgePricing.ProtoReflect.Descriptor instead.
func (*PdfDecomposeHedgePricing) Descriptor() ([]byte, []int) {
	return file_kdo_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *PdfDecomposeHedgePricing) GetRatioPerShare() float64 {
	if x != nil {
		return x.RatioPerShare
	}
	return 0
}

var File_kdo_v1_common_proto protoreflect.FileDescriptor

var file_kdo_v1_common_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6b, 0x64, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6b, 0x64, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0xaa, 0x03, 0x0a, 0x0a, 0x45, 0x74, 0x66, 0x50, 0x72, 0x69, 0x63,
	0x69, 0x6e, 0x67, 0x12, 0x47, 0x0a, 0x0d, 0x70, 0x64, 0x66, 0x5f, 0x6e, 0x61, 0x76, 0x5f, 0x68,
	0x65, 0x64, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6b, 0x64, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x64, 0x66, 0x4e, 0x61,
	0x76, 0x48, 0x65, 0x64, 0x67, 0x65, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52,
	0x0b, 0x70, 0x64, 0x66, 0x4e, 0x61, 0x76, 0x48, 0x65, 0x64, 0x67, 0x65, 0x12, 0x5c, 0x0a, 0x14,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x68,
	0x65, 0x64, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6b, 0x64, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x48, 0x65, 0x64, 0x67, 0x65, 0x50, 0x72, 0x69,
	0x63, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x12, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x69, 0x6e, 0x67, 0x48, 0x65, 0x64, 0x67, 0x65, 0x12, 0x3f, 0x0a, 0x0c, 0x66, 0x75,
	0x74, 0x75, 0x72, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x69, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x6b, 0x64, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x73, 0x48, 0x00, 0x52, 0x0b,
	0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x42, 0x61, 0x73, 0x69, 0x73, 0x12, 0x4f, 0x0a, 0x0f, 0x6c,
	0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6b, 0x64, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x46, 0x75, 0x74,
	0x75, 0x72, 0x65, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x0e, 0x6c, 0x65,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x12, 0x59, 0x0a, 0x13,
	0x70, 0x64, 0x66, 0x5f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x5f, 0x68, 0x65,
	0x64, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6b, 0x64, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x64, 0x66, 0x44, 0x65, 0x63,
	0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x48, 0x65, 0x64, 0x67, 0x65, 0x50, 0x72, 0x69, 0x63, 0x69,
	0x6e, 0x67, 0x48, 0x00, 0x52, 0x11, 0x70, 0x64, 0x66, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f,
	0x73, 0x65, 0x48, 0x65, 0x64, 0x67, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x22, 0x14, 0x0a, 0x12, 0x50, 0x64, 0x66, 0x4e, 0x61, 0x76, 0x48, 0x65, 0x64, 0x67, 0x65,
	0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x22, 0x1b, 0x0a, 0x19, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x48, 0x65, 0x64, 0x67, 0x65, 0x50, 0x72, 0x69,
	0x63, 0x69, 0x6e, 0x67, 0x22, 0x2c, 0x0a, 0x0b, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x42, 0x61,
	0x73, 0x69, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x65, 0x76, 0x5f, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x65, 0x76, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x22, 0x57, 0x0a, 0x15, 0x4c, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x46, 0x75,
	0x74, 0x75, 0x72, 0x65, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x72, 0x65, 0x76, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x09, 0x70, 0x72, 0x65, 0x76, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72,
	0x65, 0x76, 0x5f, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0a, 0x70, 0x72, 0x65, 0x76, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x22, 0x42, 0x0a, 0x18, 0x50,
	0x64, 0x66, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x48, 0x65, 0x64, 0x67, 0x65,
	0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x12, 0x26, 0x0a, 0x0f, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x5f, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0d, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x50, 0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x65, 0x2a,
	0x4f, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x69, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x16,
	0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x53, 0x49, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x52, 0x44, 0x45,
	0x52, 0x5f, 0x53, 0x49, 0x44, 0x45, 0x5f, 0x42, 0x49, 0x44, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e,
	0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x53, 0x49, 0x44, 0x45, 0x5f, 0x41, 0x53, 0x4b, 0x10, 0x02,
	0x2a, 0x74, 0x0a, 0x0a, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b,
	0x0a, 0x17, 0x4d, 0x41, 0x52, 0x4b, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x4d,
	0x41, 0x52, 0x4b, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4b, 0x4f, 0x53, 0x50, 0x49,
	0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x4d, 0x41, 0x52, 0x4b, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x4b, 0x4f, 0x53, 0x44, 0x41, 0x51, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x4d, 0x41,
	0x52, 0x4b, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x45, 0x52, 0x49, 0x56, 0x41,
	0x54, 0x49, 0x56, 0x45, 0x10, 0x03, 0x2a, 0x8a, 0x01, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x50, 0x52, 0x4f, 0x44, 0x55, 0x43,
	0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x52, 0x4f, 0x44, 0x55, 0x43, 0x54, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x54, 0x4f, 0x43, 0x4b, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14,
	0x50, 0x52, 0x4f, 0x44, 0x55, 0x43, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x55, 0x54,
	0x55, 0x52, 0x45, 0x53, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x52, 0x4f, 0x44, 0x55, 0x43,
	0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x54, 0x46, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11,
	0x50, 0x52, 0x4f, 0x44, 0x55, 0x43, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x41, 0x53,
	0x48, 0x10, 0x04, 0x2a, 0xd4, 0x01, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x1b, 0x54, 0x52, 0x41, 0x44, 0x49, 0x4e,
	0x47, 0x5f, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x54, 0x52, 0x41, 0x44, 0x49,
	0x4e, 0x47, 0x5f, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x52, 0x45, 0x5f, 0x4d,
	0x41, 0x52, 0x4b, 0x45, 0x54, 0x10, 0x01, 0x12, 0x23, 0x0a, 0x1f, 0x54, 0x52, 0x41, 0x44, 0x49,
	0x4e, 0x47, 0x5f, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x49,
	0x4e, 0x47, 0x5f, 0x41, 0x55, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17,
	0x54, 0x52, 0x41, 0x44, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f,
	0x52, 0x45, 0x47, 0x55, 0x4c, 0x41, 0x52, 0x10, 0x03, 0x12, 0x23, 0x0a, 0x1f, 0x54, 0x52, 0x41,
	0x44, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x43, 0x4c, 0x4f,
	0x53, 0x49, 0x4e, 0x47, 0x5f, 0x41, 0x55, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x04, 0x12, 0x1a,
	0x0a, 0x16, 0x54, 0x52, 0x41, 0x44, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f,
	0x4e, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x44, 0x10, 0x05, 0x2a, 0x94, 0x01, 0x0a, 0x12, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x24, 0x0a, 0x20, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4e, 0x44, 0x49,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x4f, 0x52, 0x44, 0x45, 0x52,
	0x5f, 0x43, 0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x46, 0x41, 0x53, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x43,
	0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x41,
	0x4b, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4e,
	0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x4f, 0x4b, 0x10,
	0x03, 0x2a, 0xdc, 0x01, 0x0a, 0x0f, 0x41, 0x6d, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x1d, 0x41, 0x4d, 0x45, 0x4e, 0x44, 0x5f, 0x4d,
	0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x20, 0x0a, 0x1c, 0x41, 0x4d, 0x45, 0x4e,
	0x44, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x47,
	0x47, 0x52, 0x45, 0x53, 0x53, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x41, 0x4d,
	0x45, 0x4e, 0x44, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x45, 0x56, 0x41, 0x53, 0x49, 0x56, 0x45, 0x10, 0x02, 0x12, 0x20, 0x0a, 0x1c, 0x41, 0x4d, 0x45,
	0x4e, 0x44, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42,
	0x45, 0x53, 0x54, 0x5f, 0x50, 0x52, 0x49, 0x43, 0x45, 0x10, 0x03, 0x12, 0x1f, 0x0a, 0x1b, 0x41,
	0x4d, 0x45, 0x4e, 0x44, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x53, 0x54, 0x4f, 0x50, 0x5f, 0x4c, 0x4f, 0x53, 0x53, 0x10, 0x04, 0x12, 0x22, 0x0a, 0x1e,
	0x41, 0x4d, 0x45, 0x4e, 0x44, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x44, 0x5f, 0x4d, 0x41, 0x52, 0x4b, 0x45, 0x54, 0x10, 0x05,
	0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x65, 0x72, 0x69, 0x74, 0x7a, 0x2d, 0x63, 0x6f, 0x72, 0x70, 0x2f, 0x63, 0x64, 0x73, 0x2d, 0x61,
	0x70, 0x69, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x6b, 0x64, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x6b, 0x64,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kdo_v1_common_proto_rawDescOnce sync.Once
	file_kdo_v1_common_proto_rawDescData = file_kdo_v1_common_proto_rawDesc
)

func file_kdo_v1_common_proto_rawDescGZIP() []byte {
	file_kdo_v1_common_proto_rawDescOnce.Do(func() {
		file_kdo_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_kdo_v1_common_proto_rawDescData)
	})
	return file_kdo_v1_common_proto_rawDescData
}

var file_kdo_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_kdo_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_kdo_v1_common_proto_goTypes = []interface{}{
	(OrderSide)(0),                    // 0: kdo.v1.common.OrderSide
	(MarketType)(0),                   // 1: kdo.v1.common.MarketType
	(ProductType)(0),                  // 2: kdo.v1.common.ProductType
	(TradingSession)(0),               // 3: kdo.v1.common.TradingSession
	(OrderConditionType)(0),           // 4: kdo.v1.common.OrderConditionType
	(AmendMethodType)(0),              // 5: kdo.v1.common.AmendMethodType
	(*EtfPricing)(nil),                // 6: kdo.v1.common.EtfPricing
	(*PdfNavHedgePricing)(nil),        // 7: kdo.v1.common.PdfNavHedgePricing
	(*IndexTrackingHedgePricing)(nil), // 8: kdo.v1.common.IndexTrackingHedgePricing
	(*FutureBasis)(nil),               // 9: kdo.v1.common.FutureBasis
	(*LeverageFuturePricing)(nil),     // 10: kdo.v1.common.LeverageFuturePricing
	(*PdfDecomposeHedgePricing)(nil),  // 11: kdo.v1.common.PdfDecomposeHedgePricing
}
var file_kdo_v1_common_proto_depIdxs = []int32{
	7,  // 0: kdo.v1.common.EtfPricing.pdf_nav_hedge:type_name -> kdo.v1.common.PdfNavHedgePricing
	8,  // 1: kdo.v1.common.EtfPricing.index_tracking_hedge:type_name -> kdo.v1.common.IndexTrackingHedgePricing
	9,  // 2: kdo.v1.common.EtfPricing.future_basis:type_name -> kdo.v1.common.FutureBasis
	10, // 3: kdo.v1.common.EtfPricing.leverage_future:type_name -> kdo.v1.common.LeverageFuturePricing
	11, // 4: kdo.v1.common.EtfPricing.pdf_decompose_hedge:type_name -> kdo.v1.common.PdfDecomposeHedgePricing
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_kdo_v1_common_proto_init() }
func file_kdo_v1_common_proto_init() {
	if File_kdo_v1_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kdo_v1_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EtfPricing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kdo_v1_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PdfNavHedgePricing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kdo_v1_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexTrackingHedgePricing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kdo_v1_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FutureBasis); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kdo_v1_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeverageFuturePricing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kdo_v1_common_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PdfDecomposeHedgePricing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kdo_v1_common_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*EtfPricing_PdfNavHedge)(nil),
		(*EtfPricing_IndexTrackingHedge)(nil),
		(*EtfPricing_FutureBasis)(nil),
		(*EtfPricing_LeverageFuture)(nil),
		(*EtfPricing_PdfDecomposeHedge)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kdo_v1_common_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kdo_v1_common_proto_goTypes,
		DependencyIndexes: file_kdo_v1_common_proto_depIdxs,
		EnumInfos:         file_kdo_v1_common_proto_enumTypes,
		MessageInfos:      file_kdo_v1_common_proto_msgTypes,
	}.Build()
	File_kdo_v1_common_proto = out.File
	file_kdo_v1_common_proto_rawDesc = nil
	file_kdo_v1_common_proto_goTypes = nil
	file_kdo_v1_common_proto_depIdxs = nil
}
