// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: kdo/v1/fund.proto

package kdo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FundServiceClient is the client API for FundService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FundServiceClient interface {
	// 단일 펀드 조회
	GetFund(ctx context.Context, in *GetFundRequest, opts ...grpc.CallOption) (*Fund, error)
	// 펀드 한도 조회
	GetFundLimit(ctx context.Context, in *GetFundLimitRequest, opts ...grpc.CallOption) (*GetFundLimitResponse, error)
	// 펀드 한도 스트림
	StreamFundLimit(ctx context.Context, in *GetFundLimitRequest, opts ...grpc.CallOption) (FundService_StreamFundLimitClient, error)
	// 펀드 한도 수정
	UpdateFundLimit(ctx context.Context, in *UpdateFundLimitRequest, opts ...grpc.CallOption) (*FundLimit, error)
	// 펀드 목록 조회
	ListFunds(ctx context.Context, in *ListFundsRequest, opts ...grpc.CallOption) (*ListFundsResponse, error)
	// 요청 IP 에 매핑된 펀드 목록 조회.
	// 서버가 요청 소켓의 IP → 사용자(요청자 롤) 를 확인하고, 소유자 롤이 요청자 롤과 같은
	// (= 이 IP 가 start/stop 권한을 가진) 펀드 목록을 반환한다. 파라미터 없음(IP 로 판정).
	ListFundsForCaller(ctx context.Context, in *ListFundsForCallerRequest, opts ...grpc.CallOption) (*ListFundsForCallerResponse, error)
}

type fundServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFundServiceClient(cc grpc.ClientConnInterface) FundServiceClient {
	return &fundServiceClient{cc}
}

func (c *fundServiceClient) GetFund(ctx context.Context, in *GetFundRequest, opts ...grpc.CallOption) (*Fund, error) {
	out := new(Fund)
	err := c.cc.Invoke(ctx, "/kdo.v1.fund.FundService/GetFund", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) GetFundLimit(ctx context.Context, in *GetFundLimitRequest, opts ...grpc.CallOption) (*GetFundLimitResponse, error) {
	out := new(GetFundLimitResponse)
	err := c.cc.Invoke(ctx, "/kdo.v1.fund.FundService/GetFundLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) StreamFundLimit(ctx context.Context, in *GetFundLimitRequest, opts ...grpc.CallOption) (FundService_StreamFundLimitClient, error) {
	stream, err := c.cc.NewStream(ctx, &FundService_ServiceDesc.Streams[0], "/kdo.v1.fund.FundService/StreamFundLimit", opts...)
	if err != nil {
		return nil, err
	}
	x := &fundServiceStreamFundLimitClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FundService_StreamFundLimitClient interface {
	Recv() (*GetFundLimitResponse, error)
	grpc.ClientStream
}

type fundServiceStreamFundLimitClient struct {
	grpc.ClientStream
}

func (x *fundServiceStreamFundLimitClient) Recv() (*GetFundLimitResponse, error) {
	m := new(GetFundLimitResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fundServiceClient) UpdateFundLimit(ctx context.Context, in *UpdateFundLimitRequest, opts ...grpc.CallOption) (*FundLimit, error) {
	out := new(FundLimit)
	err := c.cc.Invoke(ctx, "/kdo.v1.fund.FundService/UpdateFundLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) ListFunds(ctx context.Context, in *ListFundsRequest, opts ...grpc.CallOption) (*ListFundsResponse, error) {
	out := new(ListFundsResponse)
	err := c.cc.Invoke(ctx, "/kdo.v1.fund.FundService/ListFunds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) ListFundsForCaller(ctx context.Context, in *ListFundsForCallerRequest, opts ...grpc.CallOption) (*ListFundsForCallerResponse, error) {
	out := new(ListFundsForCallerResponse)
	err := c.cc.Invoke(ctx, "/kdo.v1.fund.FundService/ListFundsForCaller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FundServiceServer is the server API for FundService service.
// All implementations must embed UnimplementedFundServiceServer
// for forward compatibility
type FundServiceServer interface {
	// 단일 펀드 조회
	GetFund(context.Context, *GetFundRequest) (*Fund, error)
	// 펀드 한도 조회
	GetFundLimit(context.Context, *GetFundLimitRequest) (*GetFundLimitResponse, error)
	// 펀드 한도 스트림
	StreamFundLimit(*GetFundLimitRequest, FundService_StreamFundLimitServer) error
	// 펀드 한도 수정
	UpdateFundLimit(context.Context, *UpdateFundLimitRequest) (*FundLimit, error)
	// 펀드 목록 조회
	ListFunds(context.Context, *ListFundsRequest) (*ListFundsResponse, error)
	// 요청 IP 에 매핑된 펀드 목록 조회.
	// 서버가 요청 소켓의 IP → 사용자(요청자 롤) 를 확인하고, 소유자 롤이 요청자 롤과 같은
	// (= 이 IP 가 start/stop 권한을 가진) 펀드 목록을 반환한다. 파라미터 없음(IP 로 판정).
	ListFundsForCaller(context.Context, *ListFundsForCallerRequest) (*ListFundsForCallerResponse, error)
	mustEmbedUnimplementedFundServiceServer()
}

// UnimplementedFundServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFundServiceServer struct {
}

func (UnimplementedFundServiceServer) GetFund(context.Context, *GetFundRequest) (*Fund, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFund not implemented")
}
func (UnimplementedFundServiceServer) GetFundLimit(context.Context, *GetFundLimitRequest) (*GetFundLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFundLimit not implemented")
}
func (UnimplementedFundServiceServer) StreamFundLimit(*GetFundLimitRequest, FundService_StreamFundLimitServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamFundLimit not implemented")
}
func (UnimplementedFundServiceServer) UpdateFundLimit(context.Context, *UpdateFundLimitRequest) (*FundLimit, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFundLimit not implemented")
}
func (UnimplementedFundServiceServer) ListFunds(context.Context, *ListFundsRequest) (*ListFundsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFunds not implemented")
}
func (UnimplementedFundServiceServer) ListFundsForCaller(context.Context, *ListFundsForCallerRequest) (*ListFundsForCallerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFundsForCaller not implemented")
}
func (UnimplementedFundServiceServer) mustEmbedUnimplementedFundServiceServer() {}

// UnsafeFundServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FundServiceServer will
// result in compilation errors.
type UnsafeFundServiceServer interface {
	mustEmbedUnimplementedFundServiceServer()
}

func RegisterFundServiceServer(s grpc.ServiceRegistrar, srv FundServiceServer) {
	s.RegisterService(&FundService_ServiceDesc, srv)
}

func _FundService_GetFund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).GetFund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.fund.FundService/GetFund",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).GetFund(ctx, req.(*GetFundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_GetFundLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFundLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).GetFundLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.fund.FundService/GetFundLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).GetFundLimit(ctx, req.(*GetFundLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_StreamFundLimit_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetFundLimitRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FundServiceServer).StreamFundLimit(m, &fundServiceStreamFundLimitServer{stream})
}

type FundService_StreamFundLimitServer interface {
	Send(*GetFundLimitResponse) error
	grpc.ServerStream
}

type fundServiceStreamFundLimitServer struct {
	grpc.ServerStream
}

func (x *fundServiceStreamFundLimitServer) Send(m *GetFundLimitResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _FundService_UpdateFundLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFundLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).UpdateFundLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.fund.FundService/UpdateFundLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).UpdateFundLimit(ctx, req.(*UpdateFundLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_ListFunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).ListFunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.fund.FundService/ListFunds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).ListFunds(ctx, req.(*ListFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_ListFundsForCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFundsForCallerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).ListFundsForCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.fund.FundService/ListFundsForCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).ListFundsForCaller(ctx, req.(*ListFundsForCallerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FundService_ServiceDesc is the grpc.ServiceDesc for FundService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FundService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kdo.v1.fund.FundService",
	HandlerType: (*FundServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFund",
			Handler:    _FundService_GetFund_Handler,
		},
		{
			MethodName: "GetFundLimit",
			Handler:    _FundService_GetFundLimit_Handler,
		},
		{
			MethodName: "UpdateFundLimit",
			Handler:    _FundService_UpdateFundLimit_Handler,
		},
		{
			MethodName: "ListFunds",
			Handler:    _FundService_ListFunds_Handler,
		},
		{
			MethodName: "ListFundsForCaller",
			Handler:    _FundService_ListFundsForCaller_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFundLimit",
			Handler:       _FundService_StreamFundLimit_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kdo/v1/fund.proto",
}
