// Code generated by protoc-gen-go-grpc-mock. DO NOT EDIT.
// source: kdo/v1/fund.proto

package kdo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockFundServiceClient is a mock of FundServiceClient interface.
type MockFundServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockFundServiceClientMockRecorder
}

// MockFundServiceClientMockRecorder is the mock recorder for MockFundServiceClient.
type MockFundServiceClientMockRecorder struct {
	mock *MockFundServiceClient
}

// NewMockFundServiceClient creates a new mock instance.
func NewMockFundServiceClient(ctrl *gomock.Controller) *MockFundServiceClient {
	mock := &MockFundServiceClient{ctrl: ctrl}
	mock.recorder = &MockFundServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFundServiceClient) EXPECT() *MockFundServiceClientMockRecorder {
	return m.recorder
}

// GetFund mocks base method.
func (m *MockFundServiceClient) GetFund(ctx context.Context, in *GetFundRequest, opts ...grpc.CallOption) (*Fund, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFund", varargs...)
	ret0, _ := ret[0].(*Fund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFund indicates an expected call of GetFund.
func (mr *MockFundServiceClientMockRecorder) GetFund(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFund", reflect.TypeOf((*MockFundServiceClient)(nil).GetFund), varargs...)
}

// ListFunds mocks base method.
func (m *MockFundServiceClient) ListFunds(ctx context.Context, in *ListFundsRequest, opts ...grpc.CallOption) (*ListFundsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListFunds", varargs...)
	ret0, _ := ret[0].(*ListFundsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFunds indicates an expected call of ListFunds.
func (mr *MockFundServiceClientMockRecorder) ListFunds(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFunds", reflect.TypeOf((*MockFundServiceClient)(nil).ListFunds), varargs...)
}

// MockFundServiceServer is a mock of FundServiceServer interface.
type MockFundServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockFundServiceServerMockRecorder
}

// MockFundServiceServerMockRecorder is the mock recorder for MockFundServiceServer.
type MockFundServiceServerMockRecorder struct {
	mock *MockFundServiceServer
}

// NewMockFundServiceServer creates a new mock instance.
func NewMockFundServiceServer(ctrl *gomock.Controller) *MockFundServiceServer {
	mock := &MockFundServiceServer{ctrl: ctrl}
	mock.recorder = &MockFundServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFundServiceServer) EXPECT() *MockFundServiceServerMockRecorder {
	return m.recorder
}

// GetFund mocks base method.
func (m *MockFundServiceServer) GetFund(ctx context.Context, in *GetFundRequest) (*Fund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFund", ctx, in)
	ret0, _ := ret[0].(*Fund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFund indicates an expected call of GetFund.
func (mr *MockFundServiceServerMockRecorder) GetFund(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFund", reflect.TypeOf((*MockFundServiceServer)(nil).GetFund), ctx, in)
}

// ListFunds mocks base method.
func (m *MockFundServiceServer) ListFunds(ctx context.Context, in *ListFundsRequest) (*ListFundsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFunds", ctx, in)
	ret0, _ := ret[0].(*ListFundsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFunds indicates an expected call of ListFunds.
func (mr *MockFundServiceServerMockRecorder) ListFunds(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFunds", reflect.TypeOf((*MockFundServiceServer)(nil).ListFunds), ctx, in)
}
