// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: kdo/v1/fx.proto

package kdo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FxServiceClient is the client API for FxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FxServiceClient interface {
	// source_symbol/prev_close 를 presence 기반으로 부분 갱신 (없으면 생성)
	UpdateFxRate(ctx context.Context, in *UpdateFxRateRequest, opts ...grpc.CallOption) (*FxRate, error)
	// 환율 참조 설정 조회
	GetFxRate(ctx context.Context, in *GetFxRateRequest, opts ...grpc.CallOption) (*FxRate, error)
	// ETF별 환베타 설정 (master.etf.fx_beta)
	SetEtfFxBeta(ctx context.Context, in *SetEtfFxBetaRequest, opts ...grpc.CallOption) (*SetEtfFxBetaResponse, error)
}

type fxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFxServiceClient(cc grpc.ClientConnInterface) FxServiceClient {
	return &fxServiceClient{cc}
}

func (c *fxServiceClient) UpdateFxRate(ctx context.Context, in *UpdateFxRateRequest, opts ...grpc.CallOption) (*FxRate, error) {
	out := new(FxRate)
	err := c.cc.Invoke(ctx, "/kdo.v1.fx.FxService/UpdateFxRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxServiceClient) GetFxRate(ctx context.Context, in *GetFxRateRequest, opts ...grpc.CallOption) (*FxRate, error) {
	out := new(FxRate)
	err := c.cc.Invoke(ctx, "/kdo.v1.fx.FxService/GetFxRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxServiceClient) SetEtfFxBeta(ctx context.Context, in *SetEtfFxBetaRequest, opts ...grpc.CallOption) (*SetEtfFxBetaResponse, error) {
	out := new(SetEtfFxBetaResponse)
	err := c.cc.Invoke(ctx, "/kdo.v1.fx.FxService/SetEtfFxBeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FxServiceServer is the server API for FxService service.
// All implementations must embed UnimplementedFxServiceServer
// for forward compatibility
type FxServiceServer interface {
	// source_symbol/prev_close 를 presence 기반으로 부분 갱신 (없으면 생성)
	UpdateFxRate(context.Context, *UpdateFxRateRequest) (*FxRate, error)
	// 환율 참조 설정 조회
	GetFxRate(context.Context, *GetFxRateRequest) (*FxRate, error)
	// ETF별 환베타 설정 (master.etf.fx_beta)
	SetEtfFxBeta(context.Context, *SetEtfFxBetaRequest) (*SetEtfFxBetaResponse, error)
	mustEmbedUnimplementedFxServiceServer()
}

// UnimplementedFxServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFxServiceServer struct {
}

func (UnimplementedFxServiceServer) UpdateFxRate(context.Context, *UpdateFxRateRequest) (*FxRate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFxRate not implemented")
}
func (UnimplementedFxServiceServer) GetFxRate(context.Context, *GetFxRateRequest) (*FxRate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFxRate not implemented")
}
func (UnimplementedFxServiceServer) SetEtfFxBeta(context.Context, *SetEtfFxBetaRequest) (*SetEtfFxBetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEtfFxBeta not implemented")
}
func (UnimplementedFxServiceServer) mustEmbedUnimplementedFxServiceServer() {}

// UnsafeFxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FxServiceServer will
// result in compilation errors.
type UnsafeFxServiceServer interface {
	mustEmbedUnimplementedFxServiceServer()
}

func RegisterFxServiceServer(s grpc.ServiceRegistrar, srv FxServiceServer) {
	s.RegisterService(&FxService_ServiceDesc, srv)
}

func _FxService_UpdateFxRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFxRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxServiceServer).UpdateFxRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.fx.FxService/UpdateFxRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxServiceServer).UpdateFxRate(ctx, req.(*UpdateFxRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxService_GetFxRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFxRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxServiceServer).GetFxRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.fx.FxService/GetFxRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxServiceServer).GetFxRate(ctx, req.(*GetFxRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxService_SetEtfFxBeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEtfFxBetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxServiceServer).SetEtfFxBeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.fx.FxService/SetEtfFxBeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxServiceServer).SetEtfFxBeta(ctx, req.(*SetEtfFxBetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FxService_ServiceDesc is the grpc.ServiceDesc for FxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kdo.v1.fx.FxService",
	HandlerType: (*FxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateFxRate",
			Handler:    _FxService_UpdateFxRate_Handler,
		},
		{
			MethodName: "GetFxRate",
			Handler:    _FxService_GetFxRate_Handler,
		},
		{
			MethodName: "SetEtfFxBeta",
			Handler:    _FxService_SetEtfFxBeta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kdo/v1/fx.proto",
}
