// Code generated by protoc-gen-go-grpc-mock. DO NOT EDIT.
// source: kdo/v1/inventory.proto

package kdo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
)

// MockInventoryService_StreamInventoryClient is a mock of InventoryService_StreamInventoryClient interface.
type MockInventoryService_StreamInventoryClient struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryService_StreamInventoryClientMockRecorder
}

// MockInventoryService_StreamInventoryClientMockRecorder is the mock recorder for MockInventoryService_StreamInventoryClient.
type MockInventoryService_StreamInventoryClientMockRecorder struct {
	mock *MockInventoryService_StreamInventoryClient
}

// NewMockInventoryService_StreamInventoryClient creates a new mock instance.
func NewMockInventoryService_StreamInventoryClient(ctrl *gomock.Controller) *MockInventoryService_StreamInventoryClient {
	mock := &MockInventoryService_StreamInventoryClient{ctrl: ctrl}
	mock.recorder = &MockInventoryService_StreamInventoryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryService_StreamInventoryClient) EXPECT() *MockInventoryService_StreamInventoryClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockInventoryService_StreamInventoryClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockInventoryService_StreamInventoryClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockInventoryService_StreamInventoryClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockInventoryService_StreamInventoryClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockInventoryService_StreamInventoryClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockInventoryService_StreamInventoryClient)(nil).Context))
}

// Header mocks base method.
func (m *MockInventoryService_StreamInventoryClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockInventoryService_StreamInventoryClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockInventoryService_StreamInventoryClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockInventoryService_StreamInventoryClient) Recv() (*Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockInventoryService_StreamInventoryClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockInventoryService_StreamInventoryClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m *MockInventoryService_StreamInventoryClient) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockInventoryService_StreamInventoryClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockInventoryService_StreamInventoryClient)(nil).RecvMsg), arg0)
}

// SendMsg mocks base method.
func (m *MockInventoryService_StreamInventoryClient) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockInventoryService_StreamInventoryClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockInventoryService_StreamInventoryClient)(nil).SendMsg), arg0)
}

// Trailer mocks base method.
func (m *MockInventoryService_StreamInventoryClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockInventoryService_StreamInventoryClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockInventoryService_StreamInventoryClient)(nil).Trailer))
}

// MockInventoryService_StreamInventoryServer is a mock of InventoryService_StreamInventoryServer interface.
type MockInventoryService_StreamInventoryServer struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryService_StreamInventoryServerMockRecorder
}

// MockInventoryService_StreamInventoryServerMockRecorder is the mock recorder for MockInventoryService_StreamInventoryServer.
type MockInventoryService_StreamInventoryServerMockRecorder struct {
	mock *MockInventoryService_StreamInventoryServer
}

// NewMockInventoryService_StreamInventoryServer creates a new mock instance.
func NewMockInventoryService_StreamInventoryServer(ctrl *gomock.Controller) *MockInventoryService_StreamInventoryServer {
	mock := &MockInventoryService_StreamInventoryServer{ctrl: ctrl}
	mock.recorder = &MockInventoryService_StreamInventoryServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryService_StreamInventoryServer) EXPECT() *MockInventoryService_StreamInventoryServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockInventoryService_StreamInventoryServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockInventoryService_StreamInventoryServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockInventoryService_StreamInventoryServer)(nil).Context))
}

// RecvMsg mocks base method.
func (m *MockInventoryService_StreamInventoryServer) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockInventoryService_StreamInventoryServerMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockInventoryService_StreamInventoryServer)(nil).RecvMsg), arg0)
}

// Send mocks base method.
func (m *MockInventoryService_StreamInventoryServer) Send(arg0 *Inventory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockInventoryService_StreamInventoryServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockInventoryService_StreamInventoryServer)(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockInventoryService_StreamInventoryServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockInventoryService_StreamInventoryServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockInventoryService_StreamInventoryServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m *MockInventoryService_StreamInventoryServer) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockInventoryService_StreamInventoryServerMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockInventoryService_StreamInventoryServer)(nil).SendMsg), arg0)
}

// SetHeader mocks base method.
func (m *MockInventoryService_StreamInventoryServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockInventoryService_StreamInventoryServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockInventoryService_StreamInventoryServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockInventoryService_StreamInventoryServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockInventoryService_StreamInventoryServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockInventoryService_StreamInventoryServer)(nil).SetTrailer), arg0)
}

// MockInventoryServiceClient is a mock of InventoryServiceClient interface.
type MockInventoryServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryServiceClientMockRecorder
}

// MockInventoryServiceClientMockRecorder is the mock recorder for MockInventoryServiceClient.
type MockInventoryServiceClientMockRecorder struct {
	mock *MockInventoryServiceClient
}

// NewMockInventoryServiceClient creates a new mock instance.
func NewMockInventoryServiceClient(ctrl *gomock.Controller) *MockInventoryServiceClient {
	mock := &MockInventoryServiceClient{ctrl: ctrl}
	mock.recorder = &MockInventoryServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryServiceClient) EXPECT() *MockInventoryServiceClientMockRecorder {
	return m.recorder
}

// GetInventory mocks base method.
func (m *MockInventoryServiceClient) GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*Inventory, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInventory", varargs...)
	ret0, _ := ret[0].(*Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInventory indicates an expected call of GetInventory.
func (mr *MockInventoryServiceClientMockRecorder) GetInventory(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInventory", reflect.TypeOf((*MockInventoryServiceClient)(nil).GetInventory), varargs...)
}

// ListInventories mocks base method.
func (m *MockInventoryServiceClient) ListInventories(ctx context.Context, in *ListInventoriesRequest, opts ...grpc.CallOption) (*ListInventoriesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListInventories", varargs...)
	ret0, _ := ret[0].(*ListInventoriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInventories indicates an expected call of ListInventories.
func (mr *MockInventoryServiceClientMockRecorder) ListInventories(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInventories", reflect.TypeOf((*MockInventoryServiceClient)(nil).ListInventories), varargs...)
}

// StreamInventory mocks base method.
func (m *MockInventoryServiceClient) StreamInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (InventoryService_StreamInventoryClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamInventory", varargs...)
	ret0, _ := ret[0].(InventoryService_StreamInventoryClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamInventory indicates an expected call of StreamInventory.
func (mr *MockInventoryServiceClientMockRecorder) StreamInventory(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamInventory", reflect.TypeOf((*MockInventoryServiceClient)(nil).StreamInventory), varargs...)
}

// MockInventoryServiceServer is a mock of InventoryServiceServer interface.
type MockInventoryServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryServiceServerMockRecorder
}

// MockInventoryServiceServerMockRecorder is the mock recorder for MockInventoryServiceServer.
type MockInventoryServiceServerMockRecorder struct {
	mock *MockInventoryServiceServer
}

// NewMockInventoryServiceServer creates a new mock instance.
func NewMockInventoryServiceServer(ctrl *gomock.Controller) *MockInventoryServiceServer {
	mock := &MockInventoryServiceServer{ctrl: ctrl}
	mock.recorder = &MockInventoryServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryServiceServer) EXPECT() *MockInventoryServiceServerMockRecorder {
	return m.recorder
}

// GetInventory mocks base method.
func (m *MockInventoryServiceServer) GetInventory(ctx context.Context, in *GetInventoryRequest) (*Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInventory", ctx, in)
	ret0, _ := ret[0].(*Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInventory indicates an expected call of GetInventory.
func (mr *MockInventoryServiceServerMockRecorder) GetInventory(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInventory", reflect.TypeOf((*MockInventoryServiceServer)(nil).GetInventory), ctx, in)
}

// ListInventories mocks base method.
func (m *MockInventoryServiceServer) ListInventories(ctx context.Context, in *ListInventoriesRequest) (*ListInventoriesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInventories", ctx, in)
	ret0, _ := ret[0].(*ListInventoriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInventories indicates an expected call of ListInventories.
func (mr *MockInventoryServiceServerMockRecorder) ListInventories(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInventories", reflect.TypeOf((*MockInventoryServiceServer)(nil).ListInventories), ctx, in)
}

// StreamInventory mocks base method.
func (m *MockInventoryServiceServer) StreamInventory(blob *GetInventoryRequest, server InventoryService_StreamInventoryServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamInventory", blob, server)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamInventory indicates an expected call of StreamInventory.
func (mr *MockInventoryServiceServerMockRecorder) StreamInventory(blob, server interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamInventory", reflect.TypeOf((*MockInventoryServiceServer)(nil).StreamInventory), blob, server)
}
