// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: kdo/v1/market.proto

package kdo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MarketServiceClient is the client API for MarketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketServiceClient interface {
	// ETF 주문장 데이터를 스트리밍
	StreamEtfOrderbook(ctx context.Context, in *StreamEtfOrderbookRequest, opts ...grpc.CallOption) (MarketService_StreamEtfOrderbookClient, error)
	// 선물 주문장 데이터를 스트리밍
	StreamFuturesOrderbook(ctx context.Context, in *StreamFuturesOrderbookRequest, opts ...grpc.CallOption) (MarketService_StreamFuturesOrderbookClient, error)
	// ETF NAV 데이터를 스트리밍
	StreamEtfNav(ctx context.Context, in *StreamEtfNavRequest, opts ...grpc.CallOption) (MarketService_StreamEtfNavClient, error)
	// 사용자 ETF 주문장 업데이트를 가져오기
	GetUserEtfOrderbook(ctx context.Context, in *GetUserEtfOrderBookRequest, opts ...grpc.CallOption) (*UserOrderbookData, error)
	// 사용자 ETF 주문장 업데이트를 스트리밍
	StreamUserEtfOrderbook(ctx context.Context, in *GetUserEtfOrderBookRequest, opts ...grpc.CallOption) (MarketService_StreamUserEtfOrderbookClient, error)
	// 사용자 선물 주문장 업데이트를 가져오기
	GetUserFutureOrderbook(ctx context.Context, in *GetUserFutureOrderBookRequest, opts ...grpc.CallOption) (*UserOrderbookData, error)
	// 사용자 선물 주문장 업데이트를 스트리밍
	StreamUserFutureOrderbook(ctx context.Context, in *GetUserFutureOrderBookRequest, opts ...grpc.CallOption) (MarketService_StreamUserFutureOrderbookClient, error)
	// 사용자 주식 주문장 업데이트를 가져오기
	GetUserStockOrderbook(ctx context.Context, in *GetUserStockOrderBookRequest, opts ...grpc.CallOption) (*UserOrderbookData, error)
	// 사용자 주식 주문장 업데이트를 스트리밍
	StreamUserStockOrderbook(ctx context.Context, in *GetUserStockOrderBookRequest, opts ...grpc.CallOption) (MarketService_StreamUserStockOrderbookClient, error)
	// 새로운 Raw 메시지 스트리밍 UDP 소켓 추가
	AddRawMessagesSocket(ctx context.Context, in *AddRawMessagesSocketRequest, opts ...grpc.CallOption) (*AddRawMessagesSocketResponse, error)
	// Raw 메시지 스트리밍 (server-side streaming)
	StreamRawMessages(ctx context.Context, in *StreamRawMessagesRequest, opts ...grpc.CallOption) (MarketService_StreamRawMessagesClient, error)
	// 마켓 세션 정보 조회
	GetMarketSession(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMarketSessionResponse, error)
}

type marketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketServiceClient(cc grpc.ClientConnInterface) MarketServiceClient {
	return &marketServiceClient{cc}
}

func (c *marketServiceClient) StreamEtfOrderbook(ctx context.Context, in *StreamEtfOrderbookRequest, opts ...grpc.CallOption) (MarketService_StreamEtfOrderbookClient, error) {
	stream, err := c.cc.NewStream(ctx, &MarketService_ServiceDesc.Streams[0], "/kdo.v1.market.MarketService/StreamEtfOrderbook", opts...)
	if err != nil {
		return nil, err
	}
	x := &marketServiceStreamEtfOrderbookClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MarketService_StreamEtfOrderbookClient interface {
	Recv() (*EtfOrderbookData, error)
	grpc.ClientStream
}

type marketServiceStreamEtfOrderbookClient struct {
	grpc.ClientStream
}

func (x *marketServiceStreamEtfOrderbookClient) Recv() (*EtfOrderbookData, error) {
	m := new(EtfOrderbookData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *marketServiceClient) StreamFuturesOrderbook(ctx context.Context, in *StreamFuturesOrderbookRequest, opts ...grpc.CallOption) (MarketService_StreamFuturesOrderbookClient, error) {
	stream, err := c.cc.NewStream(ctx, &MarketService_ServiceDesc.Streams[1], "/kdo.v1.market.MarketService/StreamFuturesOrderbook", opts...)
	if err != nil {
		return nil, err
	}
	x := &marketServiceStreamFuturesOrderbookClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MarketService_StreamFuturesOrderbookClient interface {
	Recv() (*FuturesOrderbookData, error)
	grpc.ClientStream
}

type marketServiceStreamFuturesOrderbookClient struct {
	grpc.ClientStream
}

func (x *marketServiceStreamFuturesOrderbookClient) Recv() (*FuturesOrderbookData, error) {
	m := new(FuturesOrderbookData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *marketServiceClient) StreamEtfNav(ctx context.Context, in *StreamEtfNavRequest, opts ...grpc.CallOption) (MarketService_StreamEtfNavClient, error) {
	stream, err := c.cc.NewStream(ctx, &MarketService_ServiceDesc.Streams[2], "/kdo.v1.market.MarketService/StreamEtfNav", opts...)
	if err != nil {
		return nil, err
	}
	x := &marketServiceStreamEtfNavClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MarketService_StreamEtfNavClient interface {
	Recv() (*EtfNav, error)
	grpc.ClientStream
}

type marketServiceStreamEtfNavClient struct {
	grpc.ClientStream
}

func (x *marketServiceStreamEtfNavClient) Recv() (*EtfNav, error) {
	m := new(EtfNav)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *marketServiceClient) GetUserEtfOrderbook(ctx context.Context, in *GetUserEtfOrderBookRequest, opts ...grpc.CallOption) (*UserOrderbookData, error) {
	out := new(UserOrderbookData)
	err := c.cc.Invoke(ctx, "/kdo.v1.market.MarketService/GetUserEtfOrderbook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) StreamUserEtfOrderbook(ctx context.Context, in *GetUserEtfOrderBookRequest, opts ...grpc.CallOption) (MarketService_StreamUserEtfOrderbookClient, error) {
	stream, err := c.cc.NewStream(ctx, &MarketService_ServiceDesc.Streams[3], "/kdo.v1.market.MarketService/StreamUserEtfOrderbook", opts...)
	if err != nil {
		return nil, err
	}
	x := &marketServiceStreamUserEtfOrderbookClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MarketService_StreamUserEtfOrderbookClient interface {
	Recv() (*UserOrderbookData, error)
	grpc.ClientStream
}

type marketServiceStreamUserEtfOrderbookClient struct {
	grpc.ClientStream
}

func (x *marketServiceStreamUserEtfOrderbookClient) Recv() (*UserOrderbookData, error) {
	m := new(UserOrderbookData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *marketServiceClient) GetUserFutureOrderbook(ctx context.Context, in *GetUserFutureOrderBookRequest, opts ...grpc.CallOption) (*UserOrderbookData, error) {
	out := new(UserOrderbookData)
	err := c.cc.Invoke(ctx, "/kdo.v1.market.MarketService/GetUserFutureOrderbook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) StreamUserFutureOrderbook(ctx context.Context, in *GetUserFutureOrderBookRequest, opts ...grpc.CallOption) (MarketService_StreamUserFutureOrderbookClient, error) {
	stream, err := c.cc.NewStream(ctx, &MarketService_ServiceDesc.Streams[4], "/kdo.v1.market.MarketService/StreamUserFutureOrderbook", opts...)
	if err != nil {
		return nil, err
	}
	x := &marketServiceStreamUserFutureOrderbookClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MarketService_StreamUserFutureOrderbookClient interface {
	Recv() (*UserOrderbookData, error)
	grpc.ClientStream
}

type marketServiceStreamUserFutureOrderbookClient struct {
	grpc.ClientStream
}

func (x *marketServiceStreamUserFutureOrderbookClient) Recv() (*UserOrderbookData, error) {
	m := new(UserOrderbookData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *marketServiceClient) GetUserStockOrderbook(ctx context.Context, in *GetUserStockOrderBookRequest, opts ...grpc.CallOption) (*UserOrderbookData, error) {
	out := new(UserOrderbookData)
	err := c.cc.Invoke(ctx, "/kdo.v1.market.MarketService/GetUserStockOrderbook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) StreamUserStockOrderbook(ctx context.Context, in *GetUserStockOrderBookRequest, opts ...grpc.CallOption) (MarketService_StreamUserStockOrderbookClient, error) {
	stream, err := c.cc.NewStream(ctx, &MarketService_ServiceDesc.Streams[5], "/kdo.v1.market.MarketService/StreamUserStockOrderbook", opts...)
	if err != nil {
		return nil, err
	}
	x := &marketServiceStreamUserStockOrderbookClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MarketService_StreamUserStockOrderbookClient interface {
	Recv() (*UserOrderbookData, error)
	grpc.ClientStream
}

type marketServiceStreamUserStockOrderbookClient struct {
	grpc.ClientStream
}

func (x *marketServiceStreamUserStockOrderbookClient) Recv() (*UserOrderbookData, error) {
	m := new(UserOrderbookData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *marketServiceClient) AddRawMessagesSocket(ctx context.Context, in *AddRawMessagesSocketRequest, opts ...grpc.CallOption) (*AddRawMessagesSocketResponse, error) {
	out := new(AddRawMessagesSocketResponse)
	err := c.cc.Invoke(ctx, "/kdo.v1.market.MarketService/AddRawMessagesSocket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) StreamRawMessages(ctx context.Context, in *StreamRawMessagesRequest, opts ...grpc.CallOption) (MarketService_StreamRawMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &MarketService_ServiceDesc.Streams[6], "/kdo.v1.market.MarketService/StreamRawMessages", opts...)
	if err != nil {
		return nil, err
	}
	x := &marketServiceStreamRawMessagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MarketService_StreamRawMessagesClient interface {
	Recv() (*RawMarketMessage, error)
	grpc.ClientStream
}

type marketServiceStreamRawMessagesClient struct {
	grpc.ClientStream
}

func (x *marketServiceStreamRawMessagesClient) Recv() (*RawMarketMessage, error) {
	m := new(RawMarketMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *marketServiceClient) GetMarketSession(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMarketSessionResponse, error) {
	out := new(GetMarketSessionResponse)
	err := c.cc.Invoke(ctx, "/kdo.v1.market.MarketService/GetMarketSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketServiceServer is the server API for MarketService service.
// All implementations must embed UnimplementedMarketServiceServer
// for forward compatibility
type MarketServiceServer interface {
	// ETF 주문장 데이터를 스트리밍
	StreamEtfOrderbook(*StreamEtfOrderbookRequest, MarketService_StreamEtfOrderbookServer) error
	// 선물 주문장 데이터를 스트리밍
	StreamFuturesOrderbook(*StreamFuturesOrderbookRequest, MarketService_StreamFuturesOrderbookServer) error
	// ETF NAV 데이터를 스트리밍
	StreamEtfNav(*StreamEtfNavRequest, MarketService_StreamEtfNavServer) error
	// 사용자 ETF 주문장 업데이트를 가져오기
	GetUserEtfOrderbook(context.Context, *GetUserEtfOrderBookRequest) (*UserOrderbookData, error)
	// 사용자 ETF 주문장 업데이트를 스트리밍
	StreamUserEtfOrderbook(*GetUserEtfOrderBookRequest, MarketService_StreamUserEtfOrderbookServer) error
	// 사용자 선물 주문장 업데이트를 가져오기
	GetUserFutureOrderbook(context.Context, *GetUserFutureOrderBookRequest) (*UserOrderbookData, error)
	// 사용자 선물 주문장 업데이트를 스트리밍
	StreamUserFutureOrderbook(*GetUserFutureOrderBookRequest, MarketService_StreamUserFutureOrderbookServer) error
	// 사용자 주식 주문장 업데이트를 가져오기
	GetUserStockOrderbook(context.Context, *GetUserStockOrderBookRequest) (*UserOrderbookData, error)
	// 사용자 주식 주문장 업데이트를 스트리밍
	StreamUserStockOrderbook(*GetUserStockOrderBookRequest, MarketService_StreamUserStockOrderbookServer) error
	// 새로운 Raw 메시지 스트리밍 UDP 소켓 추가
	AddRawMessagesSocket(context.Context, *AddRawMessagesSocketRequest) (*AddRawMessagesSocketResponse, error)
	// Raw 메시지 스트리밍 (server-side streaming)
	StreamRawMessages(*StreamRawMessagesRequest, MarketService_StreamRawMessagesServer) error
	// 마켓 세션 정보 조회
	GetMarketSession(context.Context, *emptypb.Empty) (*GetMarketSessionResponse, error)
	mustEmbedUnimplementedMarketServiceServer()
}

// UnimplementedMarketServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMarketServiceServer struct {
}

func (UnimplementedMarketServiceServer) StreamEtfOrderbook(*StreamEtfOrderbookRequest, MarketService_StreamEtfOrderbookServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamEtfOrderbook not implemented")
}
func (UnimplementedMarketServiceServer) StreamFuturesOrderbook(*StreamFuturesOrderbookRequest, MarketService_StreamFuturesOrderbookServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamFuturesOrderbook not implemented")
}
func (UnimplementedMarketServiceServer) StreamEtfNav(*StreamEtfNavRequest, MarketService_StreamEtfNavServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamEtfNav not implemented")
}
func (UnimplementedMarketServiceServer) GetUserEtfOrderbook(context.Context, *GetUserEtfOrderBookRequest) (*UserOrderbookData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserEtfOrderbook not implemented")
}
func (UnimplementedMarketServiceServer) StreamUserEtfOrderbook(*GetUserEtfOrderBookRequest, MarketService_StreamUserEtfOrderbookServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamUserEtfOrderbook not implemented")
}
func (UnimplementedMarketServiceServer) GetUserFutureOrderbook(context.Context, *GetUserFutureOrderBookRequest) (*UserOrderbookData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFutureOrderbook not implemented")
}
func (UnimplementedMarketServiceServer) StreamUserFutureOrderbook(*GetUserFutureOrderBookRequest, MarketService_StreamUserFutureOrderbookServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamUserFutureOrderbook not implemented")
}
func (UnimplementedMarketServiceServer) GetUserStockOrderbook(context.Context, *GetUserStockOrderBookRequest) (*UserOrderbookData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserStockOrderbook not implemented")
}
func (UnimplementedMarketServiceServer) StreamUserStockOrderbook(*GetUserStockOrderBookRequest, MarketService_StreamUserStockOrderbookServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamUserStockOrderbook not implemented")
}
func (UnimplementedMarketServiceServer) AddRawMessagesSocket(context.Context, *AddRawMessagesSocketRequest) (*AddRawMessagesSocketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRawMessagesSocket not implemented")
}
func (UnimplementedMarketServiceServer) StreamRawMessages(*StreamRawMessagesRequest, MarketService_StreamRawMessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamRawMessages not implemented")
}
func (UnimplementedMarketServiceServer) GetMarketSession(context.Context, *emptypb.Empty) (*GetMarketSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketSession not implemented")
}
func (UnimplementedMarketServiceServer) mustEmbedUnimplementedMarketServiceServer() {}

// UnsafeMarketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketServiceServer will
// result in compilation errors.
type UnsafeMarketServiceServer interface {
	mustEmbedUnimplementedMarketServiceServer()
}

func RegisterMarketServiceServer(s grpc.ServiceRegistrar, srv MarketServiceServer) {
	s.RegisterService(&MarketService_ServiceDesc, srv)
}

func _MarketService_StreamEtfOrderbook_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEtfOrderbookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketServiceServer).StreamEtfOrderbook(m, &marketServiceStreamEtfOrderbookServer{stream})
}

type MarketService_StreamEtfOrderbookServer interface {
	Send(*EtfOrderbookData) error
	grpc.ServerStream
}

type marketServiceStreamEtfOrderbookServer struct {
	grpc.ServerStream
}

func (x *marketServiceStreamEtfOrderbookServer) Send(m *EtfOrderbookData) error {
	return x.ServerStream.SendMsg(m)
}

func _MarketService_StreamFuturesOrderbook_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamFuturesOrderbookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketServiceServer).StreamFuturesOrderbook(m, &marketServiceStreamFuturesOrderbookServer{stream})
}

type MarketService_StreamFuturesOrderbookServer interface {
	Send(*FuturesOrderbookData) error
	grpc.ServerStream
}

type marketServiceStreamFuturesOrderbookServer struct {
	grpc.ServerStream
}

func (x *marketServiceStreamFuturesOrderbookServer) Send(m *FuturesOrderbookData) error {
	return x.ServerStream.SendMsg(m)
}

func _MarketService_StreamEtfNav_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEtfNavRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketServiceServer).StreamEtfNav(m, &marketServiceStreamEtfNavServer{stream})
}

type MarketService_StreamEtfNavServer interface {
	Send(*EtfNav) error
	grpc.ServerStream
}

type marketServiceStreamEtfNavServer struct {
	grpc.ServerStream
}

func (x *marketServiceStreamEtfNavServer) Send(m *EtfNav) error {
	return x.ServerStream.SendMsg(m)
}

func _MarketService_GetUserEtfOrderbook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserEtfOrderBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetUserEtfOrderbook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.market.MarketService/GetUserEtfOrderbook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetUserEtfOrderbook(ctx, req.(*GetUserEtfOrderBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_StreamUserEtfOrderbook_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetUserEtfOrderBookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketServiceServer).StreamUserEtfOrderbook(m, &marketServiceStreamUserEtfOrderbookServer{stream})
}

type MarketService_StreamUserEtfOrderbookServer interface {
	Send(*UserOrderbookData) error
	grpc.ServerStream
}

type marketServiceStreamUserEtfOrderbookServer struct {
	grpc.ServerStream
}

func (x *marketServiceStreamUserEtfOrderbookServer) Send(m *UserOrderbookData) error {
	return x.ServerStream.SendMsg(m)
}

func _MarketService_GetUserFutureOrderbook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserFutureOrderBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetUserFutureOrderbook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.market.MarketService/GetUserFutureOrderbook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetUserFutureOrderbook(ctx, req.(*GetUserFutureOrderBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_StreamUserFutureOrderbook_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetUserFutureOrderBookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketServiceServer).StreamUserFutureOrderbook(m, &marketServiceStreamUserFutureOrderbookServer{stream})
}

type MarketService_StreamUserFutureOrderbookServer interface {
	Send(*UserOrderbookData) error
	grpc.ServerStream
}

type marketServiceStreamUserFutureOrderbookServer struct {
	grpc.ServerStream
}

func (x *marketServiceStreamUserFutureOrderbookServer) Send(m *UserOrderbookData) error {
	return x.ServerStream.SendMsg(m)
}

func _MarketService_GetUserStockOrderbook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserStockOrderBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetUserStockOrderbook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.market.MarketService/GetUserStockOrderbook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetUserStockOrderbook(ctx, req.(*GetUserStockOrderBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_StreamUserStockOrderbook_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetUserStockOrderBookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketServiceServer).StreamUserStockOrderbook(m, &marketServiceStreamUserStockOrderbookServer{stream})
}

type MarketService_StreamUserStockOrderbookServer interface {
	Send(*UserOrderbookData) error
	grpc.ServerStream
}

type marketServiceStreamUserStockOrderbookServer struct {
	grpc.ServerStream
}

func (x *marketServiceStreamUserStockOrderbookServer) Send(m *UserOrderbookData) error {
	return x.ServerStream.SendMsg(m)
}

func _MarketService_AddRawMessagesSocket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRawMessagesSocketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).AddRawMessagesSocket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.market.MarketService/AddRawMessagesSocket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).AddRawMessagesSocket(ctx, req.(*AddRawMessagesSocketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_StreamRawMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRawMessagesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketServiceServer).StreamRawMessages(m, &marketServiceStreamRawMessagesServer{stream})
}

type MarketService_StreamRawMessagesServer interface {
	Send(*RawMarketMessage) error
	grpc.ServerStream
}

type marketServiceStreamRawMessagesServer struct {
	grpc.ServerStream
}

func (x *marketServiceStreamRawMessagesServer) Send(m *RawMarketMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _MarketService_GetMarketSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetMarketSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.market.MarketService/GetMarketSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetMarketSession(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketService_ServiceDesc is the grpc.ServiceDesc for MarketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kdo.v1.market.MarketService",
	HandlerType: (*MarketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserEtfOrderbook",
			Handler:    _MarketService_GetUserEtfOrderbook_Handler,
		},
		{
			MethodName: "GetUserFutureOrderbook",
			Handler:    _MarketService_GetUserFutureOrderbook_Handler,
		},
		{
			MethodName: "GetUserStockOrderbook",
			Handler:    _MarketService_GetUserStockOrderbook_Handler,
		},
		{
			MethodName: "AddRawMessagesSocket",
			Handler:    _MarketService_AddRawMessagesSocket_Handler,
		},
		{
			MethodName: "GetMarketSession",
			Handler:    _MarketService_GetMarketSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEtfOrderbook",
			Handler:       _MarketService_StreamEtfOrderbook_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamFuturesOrderbook",
			Handler:       _MarketService_StreamFuturesOrderbook_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamEtfNav",
			Handler:       _MarketService_StreamEtfNav_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamUserEtfOrderbook",
			Handler:       _MarketService_StreamUserEtfOrderbook_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamUserFutureOrderbook",
			Handler:       _MarketService_StreamUserFutureOrderbook_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamUserStockOrderbook",
			Handler:       _MarketService_StreamUserStockOrderbook_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamRawMessages",
			Handler:       _MarketService_StreamRawMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kdo/v1/market.proto",
}
