// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: kdo/v1/market_sniping.proto

package kdo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MarketSnipingServiceClient is the client API for MarketSnipingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketSnipingServiceClient interface {
	// Market Sniping 목록 조회
	ListMarketSniping(ctx context.Context, in *ListMarketSnipingRequest, opts ...grpc.CallOption) (*ListMarketSnipingResponse, error)
	// Market Sniping 단일 심볼 조회
	GetMarketSniping(ctx context.Context, in *GetMarketSnipingRequest, opts ...grpc.CallOption) (*MarketSnipingEntry, error)
	// Market Sniping 설정 생성 (DB 저장)
	CreateMarketSniping(ctx context.Context, in *CreateMarketSnipingRequest, opts ...grpc.CallOption) (*MarketSnipingEntry, error)
	// Market Sniping 설정 업데이트 (DB 저장)
	UpdateMarketSniping(ctx context.Context, in *UpdateMarketSnipingRequest, opts ...grpc.CallOption) (*MarketSnipingEntry, error)
	// Market Sniping 삭제
	DeleteMarketSniping(ctx context.Context, in *DeleteMarketSnipingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Market Sniping 시작 (심볼 등록)
	StartMarketSniping(ctx context.Context, in *StartMarketSnipingRequest, opts ...grpc.CallOption) (*StartMarketSnipingResponse, error)
	// Market Sniping 중지 (심볼 해제)
	StopMarketSniping(ctx context.Context, in *StopMarketSnipingRequest, opts ...grpc.CallOption) (*StopMarketSnipingResponse, error)
	// Market Sniping 런타임 상태 조회
	GetMarketSnipingStatus(ctx context.Context, in *GetMarketSnipingStatusRequest, opts ...grpc.CallOption) (*MarketSnipingStatusMessage, error)
	// Market Sniping 실시간 상태 스트리밍 (서버→클라이언트)
	StreamMarketSnipingStatus(ctx context.Context, in *StreamMarketSnipingStatusRequest, opts ...grpc.CallOption) (MarketSnipingService_StreamMarketSnipingStatusClient, error)
	// 엔진 런타임 상태 스트리밍 (1초 간격 폴링)
	StreamSnipingEngineState(ctx context.Context, in *StreamSnipingEngineStateRequest, opts ...grpc.CallOption) (MarketSnipingService_StreamSnipingEngineStateClient, error)
}

type marketSnipingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketSnipingServiceClient(cc grpc.ClientConnInterface) MarketSnipingServiceClient {
	return &marketSnipingServiceClient{cc}
}

func (c *marketSnipingServiceClient) ListMarketSniping(ctx context.Context, in *ListMarketSnipingRequest, opts ...grpc.CallOption) (*ListMarketSnipingResponse, error) {
	out := new(ListMarketSnipingResponse)
	err := c.cc.Invoke(ctx, "/kdo.v1.market_sniping.MarketSnipingService/ListMarketSniping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketSnipingServiceClient) GetMarketSniping(ctx context.Context, in *GetMarketSnipingRequest, opts ...grpc.CallOption) (*MarketSnipingEntry, error) {
	out := new(MarketSnipingEntry)
	err := c.cc.Invoke(ctx, "/kdo.v1.market_sniping.MarketSnipingService/GetMarketSniping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketSnipingServiceClient) CreateMarketSniping(ctx context.Context, in *CreateMarketSnipingRequest, opts ...grpc.CallOption) (*MarketSnipingEntry, error) {
	out := new(MarketSnipingEntry)
	err := c.cc.Invoke(ctx, "/kdo.v1.market_sniping.MarketSnipingService/CreateMarketSniping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketSnipingServiceClient) UpdateMarketSniping(ctx context.Context, in *UpdateMarketSnipingRequest, opts ...grpc.CallOption) (*MarketSnipingEntry, error) {
	out := new(MarketSnipingEntry)
	err := c.cc.Invoke(ctx, "/kdo.v1.market_sniping.MarketSnipingService/UpdateMarketSniping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketSnipingServiceClient) DeleteMarketSniping(ctx context.Context, in *DeleteMarketSnipingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/kdo.v1.market_sniping.MarketSnipingService/DeleteMarketSniping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketSnipingServiceClient) StartMarketSniping(ctx context.Context, in *StartMarketSnipingRequest, opts ...grpc.CallOption) (*StartMarketSnipingResponse, error) {
	out := new(StartMarketSnipingResponse)
	err := c.cc.Invoke(ctx, "/kdo.v1.market_sniping.MarketSnipingService/StartMarketSniping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketSnipingServiceClient) StopMarketSniping(ctx context.Context, in *StopMarketSnipingRequest, opts ...grpc.CallOption) (*StopMarketSnipingResponse, error) {
	out := new(StopMarketSnipingResponse)
	err := c.cc.Invoke(ctx, "/kdo.v1.market_sniping.MarketSnipingService/StopMarketSniping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketSnipingServiceClient) GetMarketSnipingStatus(ctx context.Context, in *GetMarketSnipingStatusRequest, opts ...grpc.CallOption) (*MarketSnipingStatusMessage, error) {
	out := new(MarketSnipingStatusMessage)
	err := c.cc.Invoke(ctx, "/kdo.v1.market_sniping.MarketSnipingService/GetMarketSnipingStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketSnipingServiceClient) StreamMarketSnipingStatus(ctx context.Context, in *StreamMarketSnipingStatusRequest, opts ...grpc.CallOption) (MarketSnipingService_StreamMarketSnipingStatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &MarketSnipingService_ServiceDesc.Streams[0], "/kdo.v1.market_sniping.MarketSnipingService/StreamMarketSnipingStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &marketSnipingServiceStreamMarketSnipingStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MarketSnipingService_StreamMarketSnipingStatusClient interface {
	Recv() (*MarketSnipingStatusMessage, error)
	grpc.ClientStream
}

type marketSnipingServiceStreamMarketSnipingStatusClient struct {
	grpc.ClientStream
}

func (x *marketSnipingServiceStreamMarketSnipingStatusClient) Recv() (*MarketSnipingStatusMessage, error) {
	m := new(MarketSnipingStatusMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *marketSnipingServiceClient) StreamSnipingEngineState(ctx context.Context, in *StreamSnipingEngineStateRequest, opts ...grpc.CallOption) (MarketSnipingService_StreamSnipingEngineStateClient, error) {
	stream, err := c.cc.NewStream(ctx, &MarketSnipingService_ServiceDesc.Streams[1], "/kdo.v1.market_sniping.MarketSnipingService/StreamSnipingEngineState", opts...)
	if err != nil {
		return nil, err
	}
	x := &marketSnipingServiceStreamSnipingEngineStateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MarketSnipingService_StreamSnipingEngineStateClient interface {
	Recv() (*SnipingEngineRuntimeState, error)
	grpc.ClientStream
}

type marketSnipingServiceStreamSnipingEngineStateClient struct {
	grpc.ClientStream
}

func (x *marketSnipingServiceStreamSnipingEngineStateClient) Recv() (*SnipingEngineRuntimeState, error) {
	m := new(SnipingEngineRuntimeState)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MarketSnipingServiceServer is the server API for MarketSnipingService service.
// All implementations must embed UnimplementedMarketSnipingServiceServer
// for forward compatibility
type MarketSnipingServiceServer interface {
	// Market Sniping 목록 조회
	ListMarketSniping(context.Context, *ListMarketSnipingRequest) (*ListMarketSnipingResponse, error)
	// Market Sniping 단일 심볼 조회
	GetMarketSniping(context.Context, *GetMarketSnipingRequest) (*MarketSnipingEntry, error)
	// Market Sniping 설정 생성 (DB 저장)
	CreateMarketSniping(context.Context, *CreateMarketSnipingRequest) (*MarketSnipingEntry, error)
	// Market Sniping 설정 업데이트 (DB 저장)
	UpdateMarketSniping(context.Context, *UpdateMarketSnipingRequest) (*MarketSnipingEntry, error)
	// Market Sniping 삭제
	DeleteMarketSniping(context.Context, *DeleteMarketSnipingRequest) (*emptypb.Empty, error)
	// Market Sniping 시작 (심볼 등록)
	StartMarketSniping(context.Context, *StartMarketSnipingRequest) (*StartMarketSnipingResponse, error)
	// Market Sniping 중지 (심볼 해제)
	StopMarketSniping(context.Context, *StopMarketSnipingRequest) (*StopMarketSnipingResponse, error)
	// Market Sniping 런타임 상태 조회
	GetMarketSnipingStatus(context.Context, *GetMarketSnipingStatusRequest) (*MarketSnipingStatusMessage, error)
	// Market Sniping 실시간 상태 스트리밍 (서버→클라이언트)
	StreamMarketSnipingStatus(*StreamMarketSnipingStatusRequest, MarketSnipingService_StreamMarketSnipingStatusServer) error
	// 엔진 런타임 상태 스트리밍 (1초 간격 폴링)
	StreamSnipingEngineState(*StreamSnipingEngineStateRequest, MarketSnipingService_StreamSnipingEngineStateServer) error
	mustEmbedUnimplementedMarketSnipingServiceServer()
}

// UnimplementedMarketSnipingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMarketSnipingServiceServer struct {
}

func (UnimplementedMarketSnipingServiceServer) ListMarketSniping(context.Context, *ListMarketSnipingRequest) (*ListMarketSnipingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMarketSniping not implemented")
}
func (UnimplementedMarketSnipingServiceServer) GetMarketSniping(context.Context, *GetMarketSnipingRequest) (*MarketSnipingEntry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketSniping not implemented")
}
func (UnimplementedMarketSnipingServiceServer) CreateMarketSniping(context.Context, *CreateMarketSnipingRequest) (*MarketSnipingEntry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMarketSniping not implemented")
}
func (UnimplementedMarketSnipingServiceServer) UpdateMarketSniping(context.Context, *UpdateMarketSnipingRequest) (*MarketSnipingEntry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMarketSniping not implemented")
}
func (UnimplementedMarketSnipingServiceServer) DeleteMarketSniping(context.Context, *DeleteMarketSnipingRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMarketSniping not implemented")
}
func (UnimplementedMarketSnipingServiceServer) StartMarketSniping(context.Context, *StartMarketSnipingRequest) (*StartMarketSnipingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartMarketSniping not implemented")
}
func (UnimplementedMarketSnipingServiceServer) StopMarketSniping(context.Context, *StopMarketSnipingRequest) (*StopMarketSnipingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopMarketSniping not implemented")
}
func (UnimplementedMarketSnipingServiceServer) GetMarketSnipingStatus(context.Context, *GetMarketSnipingStatusRequest) (*MarketSnipingStatusMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketSnipingStatus not implemented")
}
func (UnimplementedMarketSnipingServiceServer) StreamMarketSnipingStatus(*StreamMarketSnipingStatusRequest, MarketSnipingService_StreamMarketSnipingStatusServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMarketSnipingStatus not implemented")
}
func (UnimplementedMarketSnipingServiceServer) StreamSnipingEngineState(*StreamSnipingEngineStateRequest, MarketSnipingService_StreamSnipingEngineStateServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamSnipingEngineState not implemented")
}
func (UnimplementedMarketSnipingServiceServer) mustEmbedUnimplementedMarketSnipingServiceServer() {}

// UnsafeMarketSnipingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketSnipingServiceServer will
// result in compilation errors.
type UnsafeMarketSnipingServiceServer interface {
	mustEmbedUnimplementedMarketSnipingServiceServer()
}

func RegisterMarketSnipingServiceServer(s grpc.ServiceRegistrar, srv MarketSnipingServiceServer) {
	s.RegisterService(&MarketSnipingService_ServiceDesc, srv)
}

func _MarketSnipingService_ListMarketSniping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMarketSnipingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketSnipingServiceServer).ListMarketSniping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.market_sniping.MarketSnipingService/ListMarketSniping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketSnipingServiceServer).ListMarketSniping(ctx, req.(*ListMarketSnipingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketSnipingService_GetMarketSniping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketSnipingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketSnipingServiceServer).GetMarketSniping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.market_sniping.MarketSnipingService/GetMarketSniping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketSnipingServiceServer).GetMarketSniping(ctx, req.(*GetMarketSnipingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketSnipingService_CreateMarketSniping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMarketSnipingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketSnipingServiceServer).CreateMarketSniping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.market_sniping.MarketSnipingService/CreateMarketSniping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketSnipingServiceServer).CreateMarketSniping(ctx, req.(*CreateMarketSnipingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketSnipingService_UpdateMarketSniping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMarketSnipingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketSnipingServiceServer).UpdateMarketSniping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.market_sniping.MarketSnipingService/UpdateMarketSniping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketSnipingServiceServer).UpdateMarketSniping(ctx, req.(*UpdateMarketSnipingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketSnipingService_DeleteMarketSniping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMarketSnipingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketSnipingServiceServer).DeleteMarketSniping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.market_sniping.MarketSnipingService/DeleteMarketSniping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketSnipingServiceServer).DeleteMarketSniping(ctx, req.(*DeleteMarketSnipingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketSnipingService_StartMarketSniping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartMarketSnipingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketSnipingServiceServer).StartMarketSniping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.market_sniping.MarketSnipingService/StartMarketSniping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketSnipingServiceServer).StartMarketSniping(ctx, req.(*StartMarketSnipingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketSnipingService_StopMarketSniping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopMarketSnipingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketSnipingServiceServer).StopMarketSniping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.market_sniping.MarketSnipingService/StopMarketSniping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketSnipingServiceServer).StopMarketSniping(ctx, req.(*StopMarketSnipingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketSnipingService_GetMarketSnipingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketSnipingStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketSnipingServiceServer).GetMarketSnipingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.market_sniping.MarketSnipingService/GetMarketSnipingStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketSnipingServiceServer).GetMarketSnipingStatus(ctx, req.(*GetMarketSnipingStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketSnipingService_StreamMarketSnipingStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMarketSnipingStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketSnipingServiceServer).StreamMarketSnipingStatus(m, &marketSnipingServiceStreamMarketSnipingStatusServer{stream})
}

type MarketSnipingService_StreamMarketSnipingStatusServer interface {
	Send(*MarketSnipingStatusMessage) error
	grpc.ServerStream
}

type marketSnipingServiceStreamMarketSnipingStatusServer struct {
	grpc.ServerStream
}

func (x *marketSnipingServiceStreamMarketSnipingStatusServer) Send(m *MarketSnipingStatusMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _MarketSnipingService_StreamSnipingEngineState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamSnipingEngineStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketSnipingServiceServer).StreamSnipingEngineState(m, &marketSnipingServiceStreamSnipingEngineStateServer{stream})
}

type MarketSnipingService_StreamSnipingEngineStateServer interface {
	Send(*SnipingEngineRuntimeState) error
	grpc.ServerStream
}

type marketSnipingServiceStreamSnipingEngineStateServer struct {
	grpc.ServerStream
}

func (x *marketSnipingServiceStreamSnipingEngineStateServer) Send(m *SnipingEngineRuntimeState) error {
	return x.ServerStream.SendMsg(m)
}

// MarketSnipingService_ServiceDesc is the grpc.ServiceDesc for MarketSnipingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketSnipingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kdo.v1.market_sniping.MarketSnipingService",
	HandlerType: (*MarketSnipingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMarketSniping",
			Handler:    _MarketSnipingService_ListMarketSniping_Handler,
		},
		{
			MethodName: "GetMarketSniping",
			Handler:    _MarketSnipingService_GetMarketSniping_Handler,
		},
		{
			MethodName: "CreateMarketSniping",
			Handler:    _MarketSnipingService_CreateMarketSniping_Handler,
		},
		{
			MethodName: "UpdateMarketSniping",
			Handler:    _MarketSnipingService_UpdateMarketSniping_Handler,
		},
		{
			MethodName: "DeleteMarketSniping",
			Handler:    _MarketSnipingService_DeleteMarketSniping_Handler,
		},
		{
			MethodName: "StartMarketSniping",
			Handler:    _MarketSnipingService_StartMarketSniping_Handler,
		},
		{
			MethodName: "StopMarketSniping",
			Handler:    _MarketSnipingService_StopMarketSniping_Handler,
		},
		{
			MethodName: "GetMarketSnipingStatus",
			Handler:    _MarketSnipingService_GetMarketSnipingStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMarketSnipingStatus",
			Handler:       _MarketSnipingService_StreamMarketSnipingStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamSnipingEngineState",
			Handler:       _MarketSnipingService_StreamSnipingEngineState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kdo/v1/market_sniping.proto",
}
