// Code generated by protoc-gen-go-grpc-mock. DO NOT EDIT.
// source: kdo/v1/mm.proto

package kdo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
)

// MockMmService_StreamMmStatusClient is a mock of MmService_StreamMmStatusClient interface.
type MockMmService_StreamMmStatusClient struct {
	ctrl     *gomock.Controller
	recorder *MockMmService_StreamMmStatusClientMockRecorder
}

// MockMmService_StreamMmStatusClientMockRecorder is the mock recorder for MockMmService_StreamMmStatusClient.
type MockMmService_StreamMmStatusClientMockRecorder struct {
	mock *MockMmService_StreamMmStatusClient
}

// NewMockMmService_StreamMmStatusClient creates a new mock instance.
func NewMockMmService_StreamMmStatusClient(ctrl *gomock.Controller) *MockMmService_StreamMmStatusClient {
	mock := &MockMmService_StreamMmStatusClient{ctrl: ctrl}
	mock.recorder = &MockMmService_StreamMmStatusClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMmService_StreamMmStatusClient) EXPECT() *MockMmService_StreamMmStatusClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockMmService_StreamMmStatusClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockMmService_StreamMmStatusClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockMmService_StreamMmStatusClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockMmService_StreamMmStatusClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockMmService_StreamMmStatusClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockMmService_StreamMmStatusClient)(nil).Context))
}

// Header mocks base method.
func (m *MockMmService_StreamMmStatusClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockMmService_StreamMmStatusClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockMmService_StreamMmStatusClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockMmService_StreamMmStatusClient) Recv() (*MmStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*MmStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockMmService_StreamMmStatusClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockMmService_StreamMmStatusClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m *MockMmService_StreamMmStatusClient) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockMmService_StreamMmStatusClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockMmService_StreamMmStatusClient)(nil).RecvMsg), arg0)
}

// SendMsg mocks base method.
func (m *MockMmService_StreamMmStatusClient) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockMmService_StreamMmStatusClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockMmService_StreamMmStatusClient)(nil).SendMsg), arg0)
}

// Trailer mocks base method.
func (m *MockMmService_StreamMmStatusClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockMmService_StreamMmStatusClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockMmService_StreamMmStatusClient)(nil).Trailer))
}

// MockMmService_StreamMmStatusServer is a mock of MmService_StreamMmStatusServer interface.
type MockMmService_StreamMmStatusServer struct {
	ctrl     *gomock.Controller
	recorder *MockMmService_StreamMmStatusServerMockRecorder
}

// MockMmService_StreamMmStatusServerMockRecorder is the mock recorder for MockMmService_StreamMmStatusServer.
type MockMmService_StreamMmStatusServerMockRecorder struct {
	mock *MockMmService_StreamMmStatusServer
}

// NewMockMmService_StreamMmStatusServer creates a new mock instance.
func NewMockMmService_StreamMmStatusServer(ctrl *gomock.Controller) *MockMmService_StreamMmStatusServer {
	mock := &MockMmService_StreamMmStatusServer{ctrl: ctrl}
	mock.recorder = &MockMmService_StreamMmStatusServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMmService_StreamMmStatusServer) EXPECT() *MockMmService_StreamMmStatusServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockMmService_StreamMmStatusServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockMmService_StreamMmStatusServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockMmService_StreamMmStatusServer)(nil).Context))
}

// RecvMsg mocks base method.
func (m *MockMmService_StreamMmStatusServer) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockMmService_StreamMmStatusServerMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockMmService_StreamMmStatusServer)(nil).RecvMsg), arg0)
}

// Send mocks base method.
func (m *MockMmService_StreamMmStatusServer) Send(arg0 *MmStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockMmService_StreamMmStatusServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMmService_StreamMmStatusServer)(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockMmService_StreamMmStatusServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockMmService_StreamMmStatusServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockMmService_StreamMmStatusServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m *MockMmService_StreamMmStatusServer) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockMmService_StreamMmStatusServerMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockMmService_StreamMmStatusServer)(nil).SendMsg), arg0)
}

// SetHeader mocks base method.
func (m *MockMmService_StreamMmStatusServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockMmService_StreamMmStatusServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockMmService_StreamMmStatusServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockMmService_StreamMmStatusServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockMmService_StreamMmStatusServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockMmService_StreamMmStatusServer)(nil).SetTrailer), arg0)
}

// MockMmService_StreamMmOrderbookClient is a mock of MmService_StreamMmOrderbookClient interface.
type MockMmService_StreamMmOrderbookClient struct {
	ctrl     *gomock.Controller
	recorder *MockMmService_StreamMmOrderbookClientMockRecorder
}

// MockMmService_StreamMmOrderbookClientMockRecorder is the mock recorder for MockMmService_StreamMmOrderbookClient.
type MockMmService_StreamMmOrderbookClientMockRecorder struct {
	mock *MockMmService_StreamMmOrderbookClient
}

// NewMockMmService_StreamMmOrderbookClient creates a new mock instance.
func NewMockMmService_StreamMmOrderbookClient(ctrl *gomock.Controller) *MockMmService_StreamMmOrderbookClient {
	mock := &MockMmService_StreamMmOrderbookClient{ctrl: ctrl}
	mock.recorder = &MockMmService_StreamMmOrderbookClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMmService_StreamMmOrderbookClient) EXPECT() *MockMmService_StreamMmOrderbookClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockMmService_StreamMmOrderbookClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockMmService_StreamMmOrderbookClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockMmService_StreamMmOrderbookClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockMmService_StreamMmOrderbookClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockMmService_StreamMmOrderbookClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockMmService_StreamMmOrderbookClient)(nil).Context))
}

// Header mocks base method.
func (m *MockMmService_StreamMmOrderbookClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockMmService_StreamMmOrderbookClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockMmService_StreamMmOrderbookClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockMmService_StreamMmOrderbookClient) Recv() (*MmOrderbookData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*MmOrderbookData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockMmService_StreamMmOrderbookClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockMmService_StreamMmOrderbookClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m *MockMmService_StreamMmOrderbookClient) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockMmService_StreamMmOrderbookClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockMmService_StreamMmOrderbookClient)(nil).RecvMsg), arg0)
}

// SendMsg mocks base method.
func (m *MockMmService_StreamMmOrderbookClient) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockMmService_StreamMmOrderbookClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockMmService_StreamMmOrderbookClient)(nil).SendMsg), arg0)
}

// Trailer mocks base method.
func (m *MockMmService_StreamMmOrderbookClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockMmService_StreamMmOrderbookClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockMmService_StreamMmOrderbookClient)(nil).Trailer))
}

// MockMmService_StreamMmOrderbookServer is a mock of MmService_StreamMmOrderbookServer interface.
type MockMmService_StreamMmOrderbookServer struct {
	ctrl     *gomock.Controller
	recorder *MockMmService_StreamMmOrderbookServerMockRecorder
}

// MockMmService_StreamMmOrderbookServerMockRecorder is the mock recorder for MockMmService_StreamMmOrderbookServer.
type MockMmService_StreamMmOrderbookServerMockRecorder struct {
	mock *MockMmService_StreamMmOrderbookServer
}

// NewMockMmService_StreamMmOrderbookServer creates a new mock instance.
func NewMockMmService_StreamMmOrderbookServer(ctrl *gomock.Controller) *MockMmService_StreamMmOrderbookServer {
	mock := &MockMmService_StreamMmOrderbookServer{ctrl: ctrl}
	mock.recorder = &MockMmService_StreamMmOrderbookServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMmService_StreamMmOrderbookServer) EXPECT() *MockMmService_StreamMmOrderbookServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockMmService_StreamMmOrderbookServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockMmService_StreamMmOrderbookServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockMmService_StreamMmOrderbookServer)(nil).Context))
}

// RecvMsg mocks base method.
func (m *MockMmService_StreamMmOrderbookServer) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockMmService_StreamMmOrderbookServerMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockMmService_StreamMmOrderbookServer)(nil).RecvMsg), arg0)
}

// Send mocks base method.
func (m *MockMmService_StreamMmOrderbookServer) Send(arg0 *MmOrderbookData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockMmService_StreamMmOrderbookServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMmService_StreamMmOrderbookServer)(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockMmService_StreamMmOrderbookServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockMmService_StreamMmOrderbookServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockMmService_StreamMmOrderbookServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m *MockMmService_StreamMmOrderbookServer) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockMmService_StreamMmOrderbookServerMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockMmService_StreamMmOrderbookServer)(nil).SendMsg), arg0)
}

// SetHeader mocks base method.
func (m *MockMmService_StreamMmOrderbookServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockMmService_StreamMmOrderbookServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockMmService_StreamMmOrderbookServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockMmService_StreamMmOrderbookServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockMmService_StreamMmOrderbookServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockMmService_StreamMmOrderbookServer)(nil).SetTrailer), arg0)
}

// MockMmServiceClient is a mock of MmServiceClient interface.
type MockMmServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockMmServiceClientMockRecorder
}

// MockMmServiceClientMockRecorder is the mock recorder for MockMmServiceClient.
type MockMmServiceClientMockRecorder struct {
	mock *MockMmServiceClient
}

// NewMockMmServiceClient creates a new mock instance.
func NewMockMmServiceClient(ctrl *gomock.Controller) *MockMmServiceClient {
	mock := &MockMmServiceClient{ctrl: ctrl}
	mock.recorder = &MockMmServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMmServiceClient) EXPECT() *MockMmServiceClientMockRecorder {
	return m.recorder
}

// CreateMm mocks base method.
func (m *MockMmServiceClient) CreateMm(ctx context.Context, in *CreateMmRequest, opts ...grpc.CallOption) (*MmEntry, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateMm", varargs...)
	ret0, _ := ret[0].(*MmEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMm indicates an expected call of CreateMm.
func (mr *MockMmServiceClientMockRecorder) CreateMm(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMm", reflect.TypeOf((*MockMmServiceClient)(nil).CreateMm), varargs...)
}

// GetMmOrderbook mocks base method.
func (m *MockMmServiceClient) GetMmOrderbook(ctx context.Context, in *GetMmOrderbookRequest, opts ...grpc.CallOption) (*MmOrderbookData, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMmOrderbook", varargs...)
	ret0, _ := ret[0].(*MmOrderbookData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMmOrderbook indicates an expected call of GetMmOrderbook.
func (mr *MockMmServiceClientMockRecorder) GetMmOrderbook(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMmOrderbook", reflect.TypeOf((*MockMmServiceClient)(nil).GetMmOrderbook), varargs...)
}

// GetMmStatus mocks base method.
func (m *MockMmServiceClient) GetMmStatus(ctx context.Context, in *GetMmStatusRequest, opts ...grpc.CallOption) (*MmStatus, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMmStatus", varargs...)
	ret0, _ := ret[0].(*MmStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMmStatus indicates an expected call of GetMmStatus.
func (mr *MockMmServiceClientMockRecorder) GetMmStatus(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMmStatus", reflect.TypeOf((*MockMmServiceClient)(nil).GetMmStatus), varargs...)
}

// ListMm mocks base method.
func (m *MockMmServiceClient) ListMm(ctx context.Context, in *ListMmRequest, opts ...grpc.CallOption) (*ListMmResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListMm", varargs...)
	ret0, _ := ret[0].(*ListMmResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMm indicates an expected call of ListMm.
func (mr *MockMmServiceClientMockRecorder) ListMm(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMm", reflect.TypeOf((*MockMmServiceClient)(nil).ListMm), varargs...)
}

// PauseMm mocks base method.
func (m *MockMmServiceClient) PauseMm(ctx context.Context, in *PauseMmRequest, opts ...grpc.CallOption) (*PauseMmResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PauseMm", varargs...)
	ret0, _ := ret[0].(*PauseMmResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PauseMm indicates an expected call of PauseMm.
func (mr *MockMmServiceClientMockRecorder) PauseMm(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseMm", reflect.TypeOf((*MockMmServiceClient)(nil).PauseMm), varargs...)
}

// ResetMm mocks base method.
func (m *MockMmServiceClient) ResetMm(ctx context.Context, in *ResetMmRequest, opts ...grpc.CallOption) (*ResetMmResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ResetMm", varargs...)
	ret0, _ := ret[0].(*ResetMmResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetMm indicates an expected call of ResetMm.
func (mr *MockMmServiceClientMockRecorder) ResetMm(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetMm", reflect.TypeOf((*MockMmServiceClient)(nil).ResetMm), varargs...)
}

// ResumeMm mocks base method.
func (m *MockMmServiceClient) ResumeMm(ctx context.Context, in *ResumeMmRequest, opts ...grpc.CallOption) (*ResumeMmResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ResumeMm", varargs...)
	ret0, _ := ret[0].(*ResumeMmResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResumeMm indicates an expected call of ResumeMm.
func (mr *MockMmServiceClientMockRecorder) ResumeMm(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeMm", reflect.TypeOf((*MockMmServiceClient)(nil).ResumeMm), varargs...)
}

// StartMm mocks base method.
func (m *MockMmServiceClient) StartMm(ctx context.Context, in *StartMmRequest, opts ...grpc.CallOption) (*StartMmResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartMm", varargs...)
	ret0, _ := ret[0].(*StartMmResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartMm indicates an expected call of StartMm.
func (mr *MockMmServiceClientMockRecorder) StartMm(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartMm", reflect.TypeOf((*MockMmServiceClient)(nil).StartMm), varargs...)
}

// StopMm mocks base method.
func (m *MockMmServiceClient) StopMm(ctx context.Context, in *StopMmRequest, opts ...grpc.CallOption) (*StopMmResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StopMm", varargs...)
	ret0, _ := ret[0].(*StopMmResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StopMm indicates an expected call of StopMm.
func (mr *MockMmServiceClientMockRecorder) StopMm(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopMm", reflect.TypeOf((*MockMmServiceClient)(nil).StopMm), varargs...)
}

// StreamMmOrderbook mocks base method.
func (m *MockMmServiceClient) StreamMmOrderbook(ctx context.Context, in *GetMmOrderbookRequest, opts ...grpc.CallOption) (MmService_StreamMmOrderbookClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamMmOrderbook", varargs...)
	ret0, _ := ret[0].(MmService_StreamMmOrderbookClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamMmOrderbook indicates an expected call of StreamMmOrderbook.
func (mr *MockMmServiceClientMockRecorder) StreamMmOrderbook(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamMmOrderbook", reflect.TypeOf((*MockMmServiceClient)(nil).StreamMmOrderbook), varargs...)
}

// StreamMmStatus mocks base method.
func (m *MockMmServiceClient) StreamMmStatus(ctx context.Context, in *StreamMmStatusRequest, opts ...grpc.CallOption) (MmService_StreamMmStatusClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamMmStatus", varargs...)
	ret0, _ := ret[0].(MmService_StreamMmStatusClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamMmStatus indicates an expected call of StreamMmStatus.
func (mr *MockMmServiceClientMockRecorder) StreamMmStatus(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamMmStatus", reflect.TypeOf((*MockMmServiceClient)(nil).StreamMmStatus), varargs...)
}

// UpdateMm mocks base method.
func (m *MockMmServiceClient) UpdateMm(ctx context.Context, in *UpdateMmRequest, opts ...grpc.CallOption) (*MmEntry, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateMm", varargs...)
	ret0, _ := ret[0].(*MmEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMm indicates an expected call of UpdateMm.
func (mr *MockMmServiceClientMockRecorder) UpdateMm(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMm", reflect.TypeOf((*MockMmServiceClient)(nil).UpdateMm), varargs...)
}

// UpdateMmConfig mocks base method.
func (m *MockMmServiceClient) UpdateMmConfig(ctx context.Context, in *UpdateMmConfigRequest, opts ...grpc.CallOption) (*MmConfiguration, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateMmConfig", varargs...)
	ret0, _ := ret[0].(*MmConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMmConfig indicates an expected call of UpdateMmConfig.
func (mr *MockMmServiceClientMockRecorder) UpdateMmConfig(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMmConfig", reflect.TypeOf((*MockMmServiceClient)(nil).UpdateMmConfig), varargs...)
}

// MockMmServiceServer is a mock of MmServiceServer interface.
type MockMmServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockMmServiceServerMockRecorder
}

// MockMmServiceServerMockRecorder is the mock recorder for MockMmServiceServer.
type MockMmServiceServerMockRecorder struct {
	mock *MockMmServiceServer
}

// NewMockMmServiceServer creates a new mock instance.
func NewMockMmServiceServer(ctrl *gomock.Controller) *MockMmServiceServer {
	mock := &MockMmServiceServer{ctrl: ctrl}
	mock.recorder = &MockMmServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMmServiceServer) EXPECT() *MockMmServiceServerMockRecorder {
	return m.recorder
}

// CreateMm mocks base method.
func (m *MockMmServiceServer) CreateMm(ctx context.Context, in *CreateMmRequest) (*MmEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMm", ctx, in)
	ret0, _ := ret[0].(*MmEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMm indicates an expected call of CreateMm.
func (mr *MockMmServiceServerMockRecorder) CreateMm(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMm", reflect.TypeOf((*MockMmServiceServer)(nil).CreateMm), ctx, in)
}

// GetMmOrderbook mocks base method.
func (m *MockMmServiceServer) GetMmOrderbook(ctx context.Context, in *GetMmOrderbookRequest) (*MmOrderbookData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMmOrderbook", ctx, in)
	ret0, _ := ret[0].(*MmOrderbookData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMmOrderbook indicates an expected call of GetMmOrderbook.
func (mr *MockMmServiceServerMockRecorder) GetMmOrderbook(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMmOrderbook", reflect.TypeOf((*MockMmServiceServer)(nil).GetMmOrderbook), ctx, in)
}

// GetMmStatus mocks base method.
func (m *MockMmServiceServer) GetMmStatus(ctx context.Context, in *GetMmStatusRequest) (*MmStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMmStatus", ctx, in)
	ret0, _ := ret[0].(*MmStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMmStatus indicates an expected call of GetMmStatus.
func (mr *MockMmServiceServerMockRecorder) GetMmStatus(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMmStatus", reflect.TypeOf((*MockMmServiceServer)(nil).GetMmStatus), ctx, in)
}

// ListMm mocks base method.
func (m *MockMmServiceServer) ListMm(ctx context.Context, in *ListMmRequest) (*ListMmResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMm", ctx, in)
	ret0, _ := ret[0].(*ListMmResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMm indicates an expected call of ListMm.
func (mr *MockMmServiceServerMockRecorder) ListMm(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMm", reflect.TypeOf((*MockMmServiceServer)(nil).ListMm), ctx, in)
}

// PauseMm mocks base method.
func (m *MockMmServiceServer) PauseMm(ctx context.Context, in *PauseMmRequest) (*PauseMmResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseMm", ctx, in)
	ret0, _ := ret[0].(*PauseMmResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PauseMm indicates an expected call of PauseMm.
func (mr *MockMmServiceServerMockRecorder) PauseMm(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseMm", reflect.TypeOf((*MockMmServiceServer)(nil).PauseMm), ctx, in)
}

// ResetMm mocks base method.
func (m *MockMmServiceServer) ResetMm(ctx context.Context, in *ResetMmRequest) (*ResetMmResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetMm", ctx, in)
	ret0, _ := ret[0].(*ResetMmResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetMm indicates an expected call of ResetMm.
func (mr *MockMmServiceServerMockRecorder) ResetMm(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetMm", reflect.TypeOf((*MockMmServiceServer)(nil).ResetMm), ctx, in)
}

// ResumeMm mocks base method.
func (m *MockMmServiceServer) ResumeMm(ctx context.Context, in *ResumeMmRequest) (*ResumeMmResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeMm", ctx, in)
	ret0, _ := ret[0].(*ResumeMmResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResumeMm indicates an expected call of ResumeMm.
func (mr *MockMmServiceServerMockRecorder) ResumeMm(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeMm", reflect.TypeOf((*MockMmServiceServer)(nil).ResumeMm), ctx, in)
}

// StartMm mocks base method.
func (m *MockMmServiceServer) StartMm(ctx context.Context, in *StartMmRequest) (*StartMmResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartMm", ctx, in)
	ret0, _ := ret[0].(*StartMmResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartMm indicates an expected call of StartMm.
func (mr *MockMmServiceServerMockRecorder) StartMm(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartMm", reflect.TypeOf((*MockMmServiceServer)(nil).StartMm), ctx, in)
}

// StopMm mocks base method.
func (m *MockMmServiceServer) StopMm(ctx context.Context, in *StopMmRequest) (*StopMmResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopMm", ctx, in)
	ret0, _ := ret[0].(*StopMmResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StopMm indicates an expected call of StopMm.
func (mr *MockMmServiceServerMockRecorder) StopMm(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopMm", reflect.TypeOf((*MockMmServiceServer)(nil).StopMm), ctx, in)
}

// StreamMmOrderbook mocks base method.
func (m *MockMmServiceServer) StreamMmOrderbook(blob *GetMmOrderbookRequest, server MmService_StreamMmOrderbookServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamMmOrderbook", blob, server)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamMmOrderbook indicates an expected call of StreamMmOrderbook.
func (mr *MockMmServiceServerMockRecorder) StreamMmOrderbook(blob, server interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamMmOrderbook", reflect.TypeOf((*MockMmServiceServer)(nil).StreamMmOrderbook), blob, server)
}

// StreamMmStatus mocks base method.
func (m *MockMmServiceServer) StreamMmStatus(blob *StreamMmStatusRequest, server MmService_StreamMmStatusServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamMmStatus", blob, server)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamMmStatus indicates an expected call of StreamMmStatus.
func (mr *MockMmServiceServerMockRecorder) StreamMmStatus(blob, server interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamMmStatus", reflect.TypeOf((*MockMmServiceServer)(nil).StreamMmStatus), blob, server)
}

// UpdateMm mocks base method.
func (m *MockMmServiceServer) UpdateMm(ctx context.Context, in *UpdateMmRequest) (*MmEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMm", ctx, in)
	ret0, _ := ret[0].(*MmEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMm indicates an expected call of UpdateMm.
func (mr *MockMmServiceServerMockRecorder) UpdateMm(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMm", reflect.TypeOf((*MockMmServiceServer)(nil).UpdateMm), ctx, in)
}

// UpdateMmConfig mocks base method.
func (m *MockMmServiceServer) UpdateMmConfig(ctx context.Context, in *UpdateMmConfigRequest) (*MmConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMmConfig", ctx, in)
	ret0, _ := ret[0].(*MmConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMmConfig indicates an expected call of UpdateMmConfig.
func (mr *MockMmServiceServerMockRecorder) UpdateMmConfig(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMmConfig", reflect.TypeOf((*MockMmServiceServer)(nil).UpdateMmConfig), ctx, in)
}
