// Code generated by protoc-gen-go-grpc-mock. DO NOT EDIT.
// source: kdo/v1/mm.proto

package kdo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
)

// MockMarketMakingService_StreamMarketMakingOrderbookClient is a mock of MarketMakingService_StreamMarketMakingOrderbookClient interface.
type MockMarketMakingService_StreamMarketMakingOrderbookClient struct {
	ctrl     *gomock.Controller
	recorder *MockMarketMakingService_StreamMarketMakingOrderbookClientMockRecorder
}

// MockMarketMakingService_StreamMarketMakingOrderbookClientMockRecorder is the mock recorder for MockMarketMakingService_StreamMarketMakingOrderbookClient.
type MockMarketMakingService_StreamMarketMakingOrderbookClientMockRecorder struct {
	mock *MockMarketMakingService_StreamMarketMakingOrderbookClient
}

// NewMockMarketMakingService_StreamMarketMakingOrderbookClient creates a new mock instance.
func NewMockMarketMakingService_StreamMarketMakingOrderbookClient(ctrl *gomock.Controller) *MockMarketMakingService_StreamMarketMakingOrderbookClient {
	mock := &MockMarketMakingService_StreamMarketMakingOrderbookClient{ctrl: ctrl}
	mock.recorder = &MockMarketMakingService_StreamMarketMakingOrderbookClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarketMakingService_StreamMarketMakingOrderbookClient) EXPECT() *MockMarketMakingService_StreamMarketMakingOrderbookClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockMarketMakingService_StreamMarketMakingOrderbookClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockMarketMakingService_StreamMarketMakingOrderbookClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockMarketMakingService_StreamMarketMakingOrderbookClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockMarketMakingService_StreamMarketMakingOrderbookClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockMarketMakingService_StreamMarketMakingOrderbookClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockMarketMakingService_StreamMarketMakingOrderbookClient)(nil).Context))
}

// Header mocks base method.
func (m *MockMarketMakingService_StreamMarketMakingOrderbookClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockMarketMakingService_StreamMarketMakingOrderbookClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockMarketMakingService_StreamMarketMakingOrderbookClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockMarketMakingService_StreamMarketMakingOrderbookClient) Recv() (*MarketMakingOrderbookData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*MarketMakingOrderbookData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockMarketMakingService_StreamMarketMakingOrderbookClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockMarketMakingService_StreamMarketMakingOrderbookClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m *MockMarketMakingService_StreamMarketMakingOrderbookClient) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockMarketMakingService_StreamMarketMakingOrderbookClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockMarketMakingService_StreamMarketMakingOrderbookClient)(nil).RecvMsg), arg0)
}

// SendMsg mocks base method.
func (m *MockMarketMakingService_StreamMarketMakingOrderbookClient) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockMarketMakingService_StreamMarketMakingOrderbookClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockMarketMakingService_StreamMarketMakingOrderbookClient)(nil).SendMsg), arg0)
}

// Trailer mocks base method.
func (m *MockMarketMakingService_StreamMarketMakingOrderbookClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockMarketMakingService_StreamMarketMakingOrderbookClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockMarketMakingService_StreamMarketMakingOrderbookClient)(nil).Trailer))
}

// MockMarketMakingService_StreamMarketMakingOrderbookServer is a mock of MarketMakingService_StreamMarketMakingOrderbookServer interface.
type MockMarketMakingService_StreamMarketMakingOrderbookServer struct {
	ctrl     *gomock.Controller
	recorder *MockMarketMakingService_StreamMarketMakingOrderbookServerMockRecorder
}

// MockMarketMakingService_StreamMarketMakingOrderbookServerMockRecorder is the mock recorder for MockMarketMakingService_StreamMarketMakingOrderbookServer.
type MockMarketMakingService_StreamMarketMakingOrderbookServerMockRecorder struct {
	mock *MockMarketMakingService_StreamMarketMakingOrderbookServer
}

// NewMockMarketMakingService_StreamMarketMakingOrderbookServer creates a new mock instance.
func NewMockMarketMakingService_StreamMarketMakingOrderbookServer(ctrl *gomock.Controller) *MockMarketMakingService_StreamMarketMakingOrderbookServer {
	mock := &MockMarketMakingService_StreamMarketMakingOrderbookServer{ctrl: ctrl}
	mock.recorder = &MockMarketMakingService_StreamMarketMakingOrderbookServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarketMakingService_StreamMarketMakingOrderbookServer) EXPECT() *MockMarketMakingService_StreamMarketMakingOrderbookServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockMarketMakingService_StreamMarketMakingOrderbookServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockMarketMakingService_StreamMarketMakingOrderbookServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockMarketMakingService_StreamMarketMakingOrderbookServer)(nil).Context))
}

// RecvMsg mocks base method.
func (m *MockMarketMakingService_StreamMarketMakingOrderbookServer) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockMarketMakingService_StreamMarketMakingOrderbookServerMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockMarketMakingService_StreamMarketMakingOrderbookServer)(nil).RecvMsg), arg0)
}

// Send mocks base method.
func (m *MockMarketMakingService_StreamMarketMakingOrderbookServer) Send(arg0 *MarketMakingOrderbookData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockMarketMakingService_StreamMarketMakingOrderbookServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMarketMakingService_StreamMarketMakingOrderbookServer)(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockMarketMakingService_StreamMarketMakingOrderbookServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockMarketMakingService_StreamMarketMakingOrderbookServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockMarketMakingService_StreamMarketMakingOrderbookServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m *MockMarketMakingService_StreamMarketMakingOrderbookServer) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockMarketMakingService_StreamMarketMakingOrderbookServerMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockMarketMakingService_StreamMarketMakingOrderbookServer)(nil).SendMsg), arg0)
}

// SetHeader mocks base method.
func (m *MockMarketMakingService_StreamMarketMakingOrderbookServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockMarketMakingService_StreamMarketMakingOrderbookServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockMarketMakingService_StreamMarketMakingOrderbookServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockMarketMakingService_StreamMarketMakingOrderbookServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockMarketMakingService_StreamMarketMakingOrderbookServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockMarketMakingService_StreamMarketMakingOrderbookServer)(nil).SetTrailer), arg0)
}

// MockMarketMakingService_StreamMmEngineStateClient is a mock of MarketMakingService_StreamMmEngineStateClient interface.
type MockMarketMakingService_StreamMmEngineStateClient struct {
	ctrl     *gomock.Controller
	recorder *MockMarketMakingService_StreamMmEngineStateClientMockRecorder
}

// MockMarketMakingService_StreamMmEngineStateClientMockRecorder is the mock recorder for MockMarketMakingService_StreamMmEngineStateClient.
type MockMarketMakingService_StreamMmEngineStateClientMockRecorder struct {
	mock *MockMarketMakingService_StreamMmEngineStateClient
}

// NewMockMarketMakingService_StreamMmEngineStateClient creates a new mock instance.
func NewMockMarketMakingService_StreamMmEngineStateClient(ctrl *gomock.Controller) *MockMarketMakingService_StreamMmEngineStateClient {
	mock := &MockMarketMakingService_StreamMmEngineStateClient{ctrl: ctrl}
	mock.recorder = &MockMarketMakingService_StreamMmEngineStateClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarketMakingService_StreamMmEngineStateClient) EXPECT() *MockMarketMakingService_StreamMmEngineStateClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockMarketMakingService_StreamMmEngineStateClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockMarketMakingService_StreamMmEngineStateClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockMarketMakingService_StreamMmEngineStateClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockMarketMakingService_StreamMmEngineStateClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockMarketMakingService_StreamMmEngineStateClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockMarketMakingService_StreamMmEngineStateClient)(nil).Context))
}

// Header mocks base method.
func (m *MockMarketMakingService_StreamMmEngineStateClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockMarketMakingService_StreamMmEngineStateClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockMarketMakingService_StreamMmEngineStateClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockMarketMakingService_StreamMmEngineStateClient) Recv() (*MmEngineRuntimeState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*MmEngineRuntimeState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockMarketMakingService_StreamMmEngineStateClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockMarketMakingService_StreamMmEngineStateClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m *MockMarketMakingService_StreamMmEngineStateClient) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockMarketMakingService_StreamMmEngineStateClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockMarketMakingService_StreamMmEngineStateClient)(nil).RecvMsg), arg0)
}

// SendMsg mocks base method.
func (m *MockMarketMakingService_StreamMmEngineStateClient) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockMarketMakingService_StreamMmEngineStateClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockMarketMakingService_StreamMmEngineStateClient)(nil).SendMsg), arg0)
}

// Trailer mocks base method.
func (m *MockMarketMakingService_StreamMmEngineStateClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockMarketMakingService_StreamMmEngineStateClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockMarketMakingService_StreamMmEngineStateClient)(nil).Trailer))
}

// MockMarketMakingService_StreamMmEngineStateServer is a mock of MarketMakingService_StreamMmEngineStateServer interface.
type MockMarketMakingService_StreamMmEngineStateServer struct {
	ctrl     *gomock.Controller
	recorder *MockMarketMakingService_StreamMmEngineStateServerMockRecorder
}

// MockMarketMakingService_StreamMmEngineStateServerMockRecorder is the mock recorder for MockMarketMakingService_StreamMmEngineStateServer.
type MockMarketMakingService_StreamMmEngineStateServerMockRecorder struct {
	mock *MockMarketMakingService_StreamMmEngineStateServer
}

// NewMockMarketMakingService_StreamMmEngineStateServer creates a new mock instance.
func NewMockMarketMakingService_StreamMmEngineStateServer(ctrl *gomock.Controller) *MockMarketMakingService_StreamMmEngineStateServer {
	mock := &MockMarketMakingService_StreamMmEngineStateServer{ctrl: ctrl}
	mock.recorder = &MockMarketMakingService_StreamMmEngineStateServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarketMakingService_StreamMmEngineStateServer) EXPECT() *MockMarketMakingService_StreamMmEngineStateServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockMarketMakingService_StreamMmEngineStateServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockMarketMakingService_StreamMmEngineStateServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockMarketMakingService_StreamMmEngineStateServer)(nil).Context))
}

// RecvMsg mocks base method.
func (m *MockMarketMakingService_StreamMmEngineStateServer) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockMarketMakingService_StreamMmEngineStateServerMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockMarketMakingService_StreamMmEngineStateServer)(nil).RecvMsg), arg0)
}

// Send mocks base method.
func (m *MockMarketMakingService_StreamMmEngineStateServer) Send(arg0 *MmEngineRuntimeState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockMarketMakingService_StreamMmEngineStateServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMarketMakingService_StreamMmEngineStateServer)(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockMarketMakingService_StreamMmEngineStateServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockMarketMakingService_StreamMmEngineStateServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockMarketMakingService_StreamMmEngineStateServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m *MockMarketMakingService_StreamMmEngineStateServer) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockMarketMakingService_StreamMmEngineStateServerMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockMarketMakingService_StreamMmEngineStateServer)(nil).SendMsg), arg0)
}

// SetHeader mocks base method.
func (m *MockMarketMakingService_StreamMmEngineStateServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockMarketMakingService_StreamMmEngineStateServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockMarketMakingService_StreamMmEngineStateServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockMarketMakingService_StreamMmEngineStateServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockMarketMakingService_StreamMmEngineStateServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockMarketMakingService_StreamMmEngineStateServer)(nil).SetTrailer), arg0)
}

// MockMarketMakingServiceClient is a mock of MarketMakingServiceClient interface.
type MockMarketMakingServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockMarketMakingServiceClientMockRecorder
}

// MockMarketMakingServiceClientMockRecorder is the mock recorder for MockMarketMakingServiceClient.
type MockMarketMakingServiceClientMockRecorder struct {
	mock *MockMarketMakingServiceClient
}

// NewMockMarketMakingServiceClient creates a new mock instance.
func NewMockMarketMakingServiceClient(ctrl *gomock.Controller) *MockMarketMakingServiceClient {
	mock := &MockMarketMakingServiceClient{ctrl: ctrl}
	mock.recorder = &MockMarketMakingServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarketMakingServiceClient) EXPECT() *MockMarketMakingServiceClientMockRecorder {
	return m.recorder
}

// GetMarketMaking mocks base method.
func (m *MockMarketMakingServiceClient) GetMarketMaking(ctx context.Context, in *GetMarketMakingRequest, opts ...grpc.CallOption) (*MarketMaking, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMarketMaking", varargs...)
	ret0, _ := ret[0].(*MarketMaking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMarketMaking indicates an expected call of GetMarketMaking.
func (mr *MockMarketMakingServiceClientMockRecorder) GetMarketMaking(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarketMaking", reflect.TypeOf((*MockMarketMakingServiceClient)(nil).GetMarketMaking), varargs...)
}

// GetMarketMakingOrderbook mocks base method.
func (m *MockMarketMakingServiceClient) GetMarketMakingOrderbook(ctx context.Context, in *GetMarketMakingOrderbookRequest, opts ...grpc.CallOption) (*MarketMakingOrderbookData, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMarketMakingOrderbook", varargs...)
	ret0, _ := ret[0].(*MarketMakingOrderbookData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMarketMakingOrderbook indicates an expected call of GetMarketMakingOrderbook.
func (mr *MockMarketMakingServiceClientMockRecorder) GetMarketMakingOrderbook(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarketMakingOrderbook", reflect.TypeOf((*MockMarketMakingServiceClient)(nil).GetMarketMakingOrderbook), varargs...)
}

// ListMarketMaking mocks base method.
func (m *MockMarketMakingServiceClient) ListMarketMaking(ctx context.Context, in *ListMarketMakingRequest, opts ...grpc.CallOption) (*ListMarketMakingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListMarketMaking", varargs...)
	ret0, _ := ret[0].(*ListMarketMakingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMarketMaking indicates an expected call of ListMarketMaking.
func (mr *MockMarketMakingServiceClientMockRecorder) ListMarketMaking(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMarketMaking", reflect.TypeOf((*MockMarketMakingServiceClient)(nil).ListMarketMaking), varargs...)
}

// StartMarketMaking mocks base method.
func (m *MockMarketMakingServiceClient) StartMarketMaking(ctx context.Context, in *StartMarketMakingRequest, opts ...grpc.CallOption) (*StartMarketMakingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartMarketMaking", varargs...)
	ret0, _ := ret[0].(*StartMarketMakingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartMarketMaking indicates an expected call of StartMarketMaking.
func (mr *MockMarketMakingServiceClientMockRecorder) StartMarketMaking(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartMarketMaking", reflect.TypeOf((*MockMarketMakingServiceClient)(nil).StartMarketMaking), varargs...)
}

// StopMarketMaking mocks base method.
func (m *MockMarketMakingServiceClient) StopMarketMaking(ctx context.Context, in *StopMarketMakingRequest, opts ...grpc.CallOption) (*StopMarketMakingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StopMarketMaking", varargs...)
	ret0, _ := ret[0].(*StopMarketMakingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StopMarketMaking indicates an expected call of StopMarketMaking.
func (mr *MockMarketMakingServiceClientMockRecorder) StopMarketMaking(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopMarketMaking", reflect.TypeOf((*MockMarketMakingServiceClient)(nil).StopMarketMaking), varargs...)
}

// StreamMarketMakingOrderbook mocks base method.
func (m *MockMarketMakingServiceClient) StreamMarketMakingOrderbook(ctx context.Context, in *GetMarketMakingOrderbookRequest, opts ...grpc.CallOption) (MarketMakingService_StreamMarketMakingOrderbookClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamMarketMakingOrderbook", varargs...)
	ret0, _ := ret[0].(MarketMakingService_StreamMarketMakingOrderbookClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamMarketMakingOrderbook indicates an expected call of StreamMarketMakingOrderbook.
func (mr *MockMarketMakingServiceClientMockRecorder) StreamMarketMakingOrderbook(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamMarketMakingOrderbook", reflect.TypeOf((*MockMarketMakingServiceClient)(nil).StreamMarketMakingOrderbook), varargs...)
}

// StreamMmEngineState mocks base method.
func (m *MockMarketMakingServiceClient) StreamMmEngineState(ctx context.Context, in *StreamMmEngineStateRequest, opts ...grpc.CallOption) (MarketMakingService_StreamMmEngineStateClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamMmEngineState", varargs...)
	ret0, _ := ret[0].(MarketMakingService_StreamMmEngineStateClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamMmEngineState indicates an expected call of StreamMmEngineState.
func (mr *MockMarketMakingServiceClientMockRecorder) StreamMmEngineState(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamMmEngineState", reflect.TypeOf((*MockMarketMakingServiceClient)(nil).StreamMmEngineState), varargs...)
}

// UpdateMarketMaking mocks base method.
func (m *MockMarketMakingServiceClient) UpdateMarketMaking(ctx context.Context, in *UpdateMarketMakingRequest, opts ...grpc.CallOption) (*MarketMaking, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateMarketMaking", varargs...)
	ret0, _ := ret[0].(*MarketMaking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMarketMaking indicates an expected call of UpdateMarketMaking.
func (mr *MockMarketMakingServiceClientMockRecorder) UpdateMarketMaking(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMarketMaking", reflect.TypeOf((*MockMarketMakingServiceClient)(nil).UpdateMarketMaking), varargs...)
}

// UpdateMarketMakingConfig mocks base method.
func (m *MockMarketMakingServiceClient) UpdateMarketMakingConfig(ctx context.Context, in *UpdateMarketMakingConfigRequest, opts ...grpc.CallOption) (*MarketMakingConfiguration, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateMarketMakingConfig", varargs...)
	ret0, _ := ret[0].(*MarketMakingConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMarketMakingConfig indicates an expected call of UpdateMarketMakingConfig.
func (mr *MockMarketMakingServiceClientMockRecorder) UpdateMarketMakingConfig(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMarketMakingConfig", reflect.TypeOf((*MockMarketMakingServiceClient)(nil).UpdateMarketMakingConfig), varargs...)
}

// MockMarketMakingServiceServer is a mock of MarketMakingServiceServer interface.
type MockMarketMakingServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockMarketMakingServiceServerMockRecorder
}

// MockMarketMakingServiceServerMockRecorder is the mock recorder for MockMarketMakingServiceServer.
type MockMarketMakingServiceServerMockRecorder struct {
	mock *MockMarketMakingServiceServer
}

// NewMockMarketMakingServiceServer creates a new mock instance.
func NewMockMarketMakingServiceServer(ctrl *gomock.Controller) *MockMarketMakingServiceServer {
	mock := &MockMarketMakingServiceServer{ctrl: ctrl}
	mock.recorder = &MockMarketMakingServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarketMakingServiceServer) EXPECT() *MockMarketMakingServiceServerMockRecorder {
	return m.recorder
}

// GetMarketMaking mocks base method.
func (m *MockMarketMakingServiceServer) GetMarketMaking(ctx context.Context, in *GetMarketMakingRequest) (*MarketMaking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMarketMaking", ctx, in)
	ret0, _ := ret[0].(*MarketMaking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMarketMaking indicates an expected call of GetMarketMaking.
func (mr *MockMarketMakingServiceServerMockRecorder) GetMarketMaking(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarketMaking", reflect.TypeOf((*MockMarketMakingServiceServer)(nil).GetMarketMaking), ctx, in)
}

// GetMarketMakingOrderbook mocks base method.
func (m *MockMarketMakingServiceServer) GetMarketMakingOrderbook(ctx context.Context, in *GetMarketMakingOrderbookRequest) (*MarketMakingOrderbookData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMarketMakingOrderbook", ctx, in)
	ret0, _ := ret[0].(*MarketMakingOrderbookData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMarketMakingOrderbook indicates an expected call of GetMarketMakingOrderbook.
func (mr *MockMarketMakingServiceServerMockRecorder) GetMarketMakingOrderbook(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarketMakingOrderbook", reflect.TypeOf((*MockMarketMakingServiceServer)(nil).GetMarketMakingOrderbook), ctx, in)
}

// ListMarketMaking mocks base method.
func (m *MockMarketMakingServiceServer) ListMarketMaking(ctx context.Context, in *ListMarketMakingRequest) (*ListMarketMakingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMarketMaking", ctx, in)
	ret0, _ := ret[0].(*ListMarketMakingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMarketMaking indicates an expected call of ListMarketMaking.
func (mr *MockMarketMakingServiceServerMockRecorder) ListMarketMaking(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMarketMaking", reflect.TypeOf((*MockMarketMakingServiceServer)(nil).ListMarketMaking), ctx, in)
}

// StartMarketMaking mocks base method.
func (m *MockMarketMakingServiceServer) StartMarketMaking(ctx context.Context, in *StartMarketMakingRequest) (*StartMarketMakingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartMarketMaking", ctx, in)
	ret0, _ := ret[0].(*StartMarketMakingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartMarketMaking indicates an expected call of StartMarketMaking.
func (mr *MockMarketMakingServiceServerMockRecorder) StartMarketMaking(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartMarketMaking", reflect.TypeOf((*MockMarketMakingServiceServer)(nil).StartMarketMaking), ctx, in)
}

// StopMarketMaking mocks base method.
func (m *MockMarketMakingServiceServer) StopMarketMaking(ctx context.Context, in *StopMarketMakingRequest) (*StopMarketMakingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopMarketMaking", ctx, in)
	ret0, _ := ret[0].(*StopMarketMakingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StopMarketMaking indicates an expected call of StopMarketMaking.
func (mr *MockMarketMakingServiceServerMockRecorder) StopMarketMaking(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopMarketMaking", reflect.TypeOf((*MockMarketMakingServiceServer)(nil).StopMarketMaking), ctx, in)
}

// StreamMarketMakingOrderbook mocks base method.
func (m *MockMarketMakingServiceServer) StreamMarketMakingOrderbook(blob *GetMarketMakingOrderbookRequest, server MarketMakingService_StreamMarketMakingOrderbookServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamMarketMakingOrderbook", blob, server)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamMarketMakingOrderbook indicates an expected call of StreamMarketMakingOrderbook.
func (mr *MockMarketMakingServiceServerMockRecorder) StreamMarketMakingOrderbook(blob, server interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamMarketMakingOrderbook", reflect.TypeOf((*MockMarketMakingServiceServer)(nil).StreamMarketMakingOrderbook), blob, server)
}

// StreamMmEngineState mocks base method.
func (m *MockMarketMakingServiceServer) StreamMmEngineState(blob *StreamMmEngineStateRequest, server MarketMakingService_StreamMmEngineStateServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamMmEngineState", blob, server)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamMmEngineState indicates an expected call of StreamMmEngineState.
func (mr *MockMarketMakingServiceServerMockRecorder) StreamMmEngineState(blob, server interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamMmEngineState", reflect.TypeOf((*MockMarketMakingServiceServer)(nil).StreamMmEngineState), blob, server)
}

// UpdateMarketMaking mocks base method.
func (m *MockMarketMakingServiceServer) UpdateMarketMaking(ctx context.Context, in *UpdateMarketMakingRequest) (*MarketMaking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMarketMaking", ctx, in)
	ret0, _ := ret[0].(*MarketMaking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMarketMaking indicates an expected call of UpdateMarketMaking.
func (mr *MockMarketMakingServiceServerMockRecorder) UpdateMarketMaking(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMarketMaking", reflect.TypeOf((*MockMarketMakingServiceServer)(nil).UpdateMarketMaking), ctx, in)
}

// UpdateMarketMakingConfig mocks base method.
func (m *MockMarketMakingServiceServer) UpdateMarketMakingConfig(ctx context.Context, in *UpdateMarketMakingConfigRequest) (*MarketMakingConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMarketMakingConfig", ctx, in)
	ret0, _ := ret[0].(*MarketMakingConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMarketMakingConfig indicates an expected call of UpdateMarketMakingConfig.
func (mr *MockMarketMakingServiceServerMockRecorder) UpdateMarketMakingConfig(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMarketMakingConfig", reflect.TypeOf((*MockMarketMakingServiceServer)(nil).UpdateMarketMakingConfig), ctx, in)
}
