// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: kdo/v1/order_log.proto

package kdo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrderLogServiceClient is the client API for OrderLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderLogServiceClient interface {
	// 주문 로그 조회
	ListOrderLogs(ctx context.Context, in *ListOrderLogsRequest, opts ...grpc.CallOption) (*ListOrderLogsResponse, error)
	// 주문 로그 조회
	StreamOrderLogs(ctx context.Context, in *ListOrderLogsRequest, opts ...grpc.CallOption) (*ListOrderLogsResponse, error)
}

type orderLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderLogServiceClient(cc grpc.ClientConnInterface) OrderLogServiceClient {
	return &orderLogServiceClient{cc}
}

func (c *orderLogServiceClient) ListOrderLogs(ctx context.Context, in *ListOrderLogsRequest, opts ...grpc.CallOption) (*ListOrderLogsResponse, error) {
	out := new(ListOrderLogsResponse)
	err := c.cc.Invoke(ctx, "/kdo.v1.order_log.OrderLogService/ListOrderLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderLogServiceClient) StreamOrderLogs(ctx context.Context, in *ListOrderLogsRequest, opts ...grpc.CallOption) (*ListOrderLogsResponse, error) {
	out := new(ListOrderLogsResponse)
	err := c.cc.Invoke(ctx, "/kdo.v1.order_log.OrderLogService/StreamOrderLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderLogServiceServer is the server API for OrderLogService service.
// All implementations must embed UnimplementedOrderLogServiceServer
// for forward compatibility
type OrderLogServiceServer interface {
	// 주문 로그 조회
	ListOrderLogs(context.Context, *ListOrderLogsRequest) (*ListOrderLogsResponse, error)
	// 주문 로그 조회
	StreamOrderLogs(context.Context, *ListOrderLogsRequest) (*ListOrderLogsResponse, error)
	mustEmbedUnimplementedOrderLogServiceServer()
}

// UnimplementedOrderLogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrderLogServiceServer struct {
}

func (UnimplementedOrderLogServiceServer) ListOrderLogs(context.Context, *ListOrderLogsRequest) (*ListOrderLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrderLogs not implemented")
}
func (UnimplementedOrderLogServiceServer) StreamOrderLogs(context.Context, *ListOrderLogsRequest) (*ListOrderLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StreamOrderLogs not implemented")
}
func (UnimplementedOrderLogServiceServer) mustEmbedUnimplementedOrderLogServiceServer() {}

// UnsafeOrderLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderLogServiceServer will
// result in compilation errors.
type UnsafeOrderLogServiceServer interface {
	mustEmbedUnimplementedOrderLogServiceServer()
}

func RegisterOrderLogServiceServer(s grpc.ServiceRegistrar, srv OrderLogServiceServer) {
	s.RegisterService(&OrderLogService_ServiceDesc, srv)
}

func _OrderLogService_ListOrderLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrderLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderLogServiceServer).ListOrderLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.order_log.OrderLogService/ListOrderLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderLogServiceServer).ListOrderLogs(ctx, req.(*ListOrderLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderLogService_StreamOrderLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrderLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderLogServiceServer).StreamOrderLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kdo.v1.order_log.OrderLogService/StreamOrderLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderLogServiceServer).StreamOrderLogs(ctx, req.(*ListOrderLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderLogService_ServiceDesc is the grpc.ServiceDesc for OrderLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kdo.v1.order_log.OrderLogService",
	HandlerType: (*OrderLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListOrderLogs",
			Handler:    _OrderLogService_ListOrderLogs_Handler,
		},
		{
			MethodName: "StreamOrderLogs",
			Handler:    _OrderLogService_StreamOrderLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kdo/v1/order_log.proto",
}
