// Code generated by protoc-gen-go-grpc-mock. DO NOT EDIT.
// source: kdo/v1/stock_inventory.proto

package kdo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
)

// MockStockInventoryService_StreamStockInventoryClient is a mock of StockInventoryService_StreamStockInventoryClient interface.
type MockStockInventoryService_StreamStockInventoryClient struct {
	ctrl     *gomock.Controller
	recorder *MockStockInventoryService_StreamStockInventoryClientMockRecorder
}

// MockStockInventoryService_StreamStockInventoryClientMockRecorder is the mock recorder for MockStockInventoryService_StreamStockInventoryClient.
type MockStockInventoryService_StreamStockInventoryClientMockRecorder struct {
	mock *MockStockInventoryService_StreamStockInventoryClient
}

// NewMockStockInventoryService_StreamStockInventoryClient creates a new mock instance.
func NewMockStockInventoryService_StreamStockInventoryClient(ctrl *gomock.Controller) *MockStockInventoryService_StreamStockInventoryClient {
	mock := &MockStockInventoryService_StreamStockInventoryClient{ctrl: ctrl}
	mock.recorder = &MockStockInventoryService_StreamStockInventoryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockInventoryService_StreamStockInventoryClient) EXPECT() *MockStockInventoryService_StreamStockInventoryClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockStockInventoryService_StreamStockInventoryClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockStockInventoryService_StreamStockInventoryClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockStockInventoryService_StreamStockInventoryClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockStockInventoryService_StreamStockInventoryClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockStockInventoryService_StreamStockInventoryClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockStockInventoryService_StreamStockInventoryClient)(nil).Context))
}

// Header mocks base method.
func (m *MockStockInventoryService_StreamStockInventoryClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockStockInventoryService_StreamStockInventoryClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockStockInventoryService_StreamStockInventoryClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockStockInventoryService_StreamStockInventoryClient) Recv() (*StockInventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*StockInventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockStockInventoryService_StreamStockInventoryClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockStockInventoryService_StreamStockInventoryClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m *MockStockInventoryService_StreamStockInventoryClient) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockStockInventoryService_StreamStockInventoryClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockStockInventoryService_StreamStockInventoryClient)(nil).RecvMsg), arg0)
}

// SendMsg mocks base method.
func (m *MockStockInventoryService_StreamStockInventoryClient) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockStockInventoryService_StreamStockInventoryClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockStockInventoryService_StreamStockInventoryClient)(nil).SendMsg), arg0)
}

// Trailer mocks base method.
func (m *MockStockInventoryService_StreamStockInventoryClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockStockInventoryService_StreamStockInventoryClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockStockInventoryService_StreamStockInventoryClient)(nil).Trailer))
}

// MockStockInventoryService_StreamStockInventoryServer is a mock of StockInventoryService_StreamStockInventoryServer interface.
type MockStockInventoryService_StreamStockInventoryServer struct {
	ctrl     *gomock.Controller
	recorder *MockStockInventoryService_StreamStockInventoryServerMockRecorder
}

// MockStockInventoryService_StreamStockInventoryServerMockRecorder is the mock recorder for MockStockInventoryService_StreamStockInventoryServer.
type MockStockInventoryService_StreamStockInventoryServerMockRecorder struct {
	mock *MockStockInventoryService_StreamStockInventoryServer
}

// NewMockStockInventoryService_StreamStockInventoryServer creates a new mock instance.
func NewMockStockInventoryService_StreamStockInventoryServer(ctrl *gomock.Controller) *MockStockInventoryService_StreamStockInventoryServer {
	mock := &MockStockInventoryService_StreamStockInventoryServer{ctrl: ctrl}
	mock.recorder = &MockStockInventoryService_StreamStockInventoryServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockInventoryService_StreamStockInventoryServer) EXPECT() *MockStockInventoryService_StreamStockInventoryServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockStockInventoryService_StreamStockInventoryServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockStockInventoryService_StreamStockInventoryServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockStockInventoryService_StreamStockInventoryServer)(nil).Context))
}

// RecvMsg mocks base method.
func (m *MockStockInventoryService_StreamStockInventoryServer) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockStockInventoryService_StreamStockInventoryServerMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockStockInventoryService_StreamStockInventoryServer)(nil).RecvMsg), arg0)
}

// Send mocks base method.
func (m *MockStockInventoryService_StreamStockInventoryServer) Send(arg0 *StockInventory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockStockInventoryService_StreamStockInventoryServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockStockInventoryService_StreamStockInventoryServer)(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockStockInventoryService_StreamStockInventoryServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockStockInventoryService_StreamStockInventoryServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockStockInventoryService_StreamStockInventoryServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m *MockStockInventoryService_StreamStockInventoryServer) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockStockInventoryService_StreamStockInventoryServerMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockStockInventoryService_StreamStockInventoryServer)(nil).SendMsg), arg0)
}

// SetHeader mocks base method.
func (m *MockStockInventoryService_StreamStockInventoryServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockStockInventoryService_StreamStockInventoryServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockStockInventoryService_StreamStockInventoryServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockStockInventoryService_StreamStockInventoryServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockStockInventoryService_StreamStockInventoryServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockStockInventoryService_StreamStockInventoryServer)(nil).SetTrailer), arg0)
}

// MockStockInventoryServiceClient is a mock of StockInventoryServiceClient interface.
type MockStockInventoryServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockStockInventoryServiceClientMockRecorder
}

// MockStockInventoryServiceClientMockRecorder is the mock recorder for MockStockInventoryServiceClient.
type MockStockInventoryServiceClientMockRecorder struct {
	mock *MockStockInventoryServiceClient
}

// NewMockStockInventoryServiceClient creates a new mock instance.
func NewMockStockInventoryServiceClient(ctrl *gomock.Controller) *MockStockInventoryServiceClient {
	mock := &MockStockInventoryServiceClient{ctrl: ctrl}
	mock.recorder = &MockStockInventoryServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockInventoryServiceClient) EXPECT() *MockStockInventoryServiceClientMockRecorder {
	return m.recorder
}

// GetStockInventory mocks base method.
func (m *MockStockInventoryServiceClient) GetStockInventory(ctx context.Context, in *GetStockInventoryRequest, opts ...grpc.CallOption) (*StockInventory, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStockInventory", varargs...)
	ret0, _ := ret[0].(*StockInventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockInventory indicates an expected call of GetStockInventory.
func (mr *MockStockInventoryServiceClientMockRecorder) GetStockInventory(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockInventory", reflect.TypeOf((*MockStockInventoryServiceClient)(nil).GetStockInventory), varargs...)
}

// ListStockInventories mocks base method.
func (m *MockStockInventoryServiceClient) ListStockInventories(ctx context.Context, in *ListStockInventoriesRequest, opts ...grpc.CallOption) (*ListStockInventoriesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListStockInventories", varargs...)
	ret0, _ := ret[0].(*ListStockInventoriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStockInventories indicates an expected call of ListStockInventories.
func (mr *MockStockInventoryServiceClientMockRecorder) ListStockInventories(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStockInventories", reflect.TypeOf((*MockStockInventoryServiceClient)(nil).ListStockInventories), varargs...)
}

// StreamStockInventory mocks base method.
func (m *MockStockInventoryServiceClient) StreamStockInventory(ctx context.Context, in *GetStockInventoryRequest, opts ...grpc.CallOption) (StockInventoryService_StreamStockInventoryClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamStockInventory", varargs...)
	ret0, _ := ret[0].(StockInventoryService_StreamStockInventoryClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamStockInventory indicates an expected call of StreamStockInventory.
func (mr *MockStockInventoryServiceClientMockRecorder) StreamStockInventory(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamStockInventory", reflect.TypeOf((*MockStockInventoryServiceClient)(nil).StreamStockInventory), varargs...)
}

// MockStockInventoryServiceServer is a mock of StockInventoryServiceServer interface.
type MockStockInventoryServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockStockInventoryServiceServerMockRecorder
}

// MockStockInventoryServiceServerMockRecorder is the mock recorder for MockStockInventoryServiceServer.
type MockStockInventoryServiceServerMockRecorder struct {
	mock *MockStockInventoryServiceServer
}

// NewMockStockInventoryServiceServer creates a new mock instance.
func NewMockStockInventoryServiceServer(ctrl *gomock.Controller) *MockStockInventoryServiceServer {
	mock := &MockStockInventoryServiceServer{ctrl: ctrl}
	mock.recorder = &MockStockInventoryServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockInventoryServiceServer) EXPECT() *MockStockInventoryServiceServerMockRecorder {
	return m.recorder
}

// GetStockInventory mocks base method.
func (m *MockStockInventoryServiceServer) GetStockInventory(ctx context.Context, in *GetStockInventoryRequest) (*StockInventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockInventory", ctx, in)
	ret0, _ := ret[0].(*StockInventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockInventory indicates an expected call of GetStockInventory.
func (mr *MockStockInventoryServiceServerMockRecorder) GetStockInventory(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockInventory", reflect.TypeOf((*MockStockInventoryServiceServer)(nil).GetStockInventory), ctx, in)
}

// ListStockInventories mocks base method.
func (m *MockStockInventoryServiceServer) ListStockInventories(ctx context.Context, in *ListStockInventoriesRequest) (*ListStockInventoriesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStockInventories", ctx, in)
	ret0, _ := ret[0].(*ListStockInventoriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStockInventories indicates an expected call of ListStockInventories.
func (mr *MockStockInventoryServiceServerMockRecorder) ListStockInventories(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStockInventories", reflect.TypeOf((*MockStockInventoryServiceServer)(nil).ListStockInventories), ctx, in)
}

// StreamStockInventory mocks base method.
func (m *MockStockInventoryServiceServer) StreamStockInventory(blob *GetStockInventoryRequest, server StockInventoryService_StreamStockInventoryServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamStockInventory", blob, server)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamStockInventory indicates an expected call of StreamStockInventory.
func (mr *MockStockInventoryServiceServerMockRecorder) StreamStockInventory(blob, server interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamStockInventory", reflect.TypeOf((*MockStockInventoryServiceServer)(nil).StreamStockInventory), blob, server)
}
